Repository aws4embeddedlinux/meta-aws, pull requests merged in 2022-12, with the labels that each got.

#1430 2022-12-01_00-11-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.20.bb
Labels: version-upgrade

#1432 2022-12-01_00-11-47_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.0.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
Labels: version-upgrade

#1434 2022-12-01_00-11-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.20.bb
Labels: version-upgrade

#1431 2022-12-01_00-11-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.20.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1433 2022-12-01_00-11-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.20.bb
Labels: version-upgrade

#1437 2022-12-01_00-11-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1435 2022-12-01_00-11-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1438 2022-12-01_00-11-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1440 2022-12-01_00-11-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1441 2022-12-01_00-11-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.20.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1443 2022-12-01_00-11-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.20.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1442 2022-12-01_00-11-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.20.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1444 2022-12-01_00-11-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1446 2022-12-01_00-11-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1439 2022-12-01_00-11-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.20.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1449 2022-12-02_00-09-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.21.bb
Labels: version-upgrade

#1450 2022-12-02_00-09-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.21.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1451 2022-12-02_00-09-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1452 2022-12-02_00-09-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1455 2022-12-02_00-09-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.21.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1454 2022-12-02_00-09-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.21.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1448 2022-12-02_00-09-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.21.bb
Labels: version-upgrade

#1453 2022-12-02_00-09-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1456 2022-12-02_00-09-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.21.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1458 2022-12-02_00-09-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1459 2022-12-02_00-09-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1457 2022-12-02_00-09-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1447 2022-12-02_00-09-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.21.bb
Labels: version-upgrade

#1461 2022-12-02_00-09-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1463 2022-12-02_00-09-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1462 2022-12-02_00-09-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1470 2022-12-03_00-09-27_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.0.bb
Labels: version-upgrade

#1466 2022-12-03_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.22.bb
Labels: version-upgrade

#1469 2022-12-03_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.22.bb
Labels: version-upgrade

#1465 2022-12-03_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.22.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1467 2022-12-03_00-09-27_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.1.bb
Labels: version-upgrade

#1472 2022-12-03_00-09-27_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1475 2022-12-03_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1471 2022-12-03_00-09-27_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.0.bb
Labels: version-upgrade

#1477 2022-12-03_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1478 2022-12-03_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1483 2022-12-03_00-09-27_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1484 2022-12-03_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.22.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1485 2022-12-03_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.22.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1486 2022-12-03_00-09-27_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1476 2022-12-03_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1479 2022-12-03_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1482 2022-12-03_00-09-27_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1464 2022-12-03_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.22.bb
Labels: version-upgrade

#1481 2022-12-03_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.22.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1491 2022-12-03_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1487 2022-12-03_00-09-27_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1489 2022-12-03_00-09-27_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1488 2022-12-03_00-09-27_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1492 2022-12-03_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1490 2022-12-03_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1473 2022-12-03_00-09-27_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1474 2022-12-03_00-09-27_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1480 2022-12-03_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1460 firecracker, jailer: upgrade + enable auto upgrade
  recipes-containers/firecracker/firecracker-0.24.3.inc
  recipes-containers/firecracker/firecracker.inc
  recipes-containers/firecracker/firecracker/0001-fdt-lib.patch
  recipes-containers/firecracker/firecracker/0002-kvm-bindings-use-local-version.patch
  recipes-containers/firecracker/firecracker/0003-Remove-abort-panic-from-the-workspace.patch
  recipes-containers/firecracker/firecracker_0.24.3.bb
  recipes-containers/firecracker/firecracker_1.2.0.bb
  recipes-containers/firecracker/jailer-0.24.3.inc
  recipes-containers/firecracker/jailer.inc
  recipes-containers/firecracker/jailer/0002-kvm-bindings-use-local-version.patch
  recipes-containers/firecracker/jailer/0003-Remove-abort-panic-from-the-workspace.patch
  recipes-containers/firecracker/jailer_0.24.3.bb
  recipes-containers/firecracker/jailer_1.2.0.bb
Labels: auto-integrate

#1496 2022-12-06_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.23.bb
Labels: version-upgrade

#1500 2022-12-06_00-09-41_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.20.0.bb
Labels: version-upgrade

#1497 2022-12-06_00-09-41_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.28.bb
Labels: version-upgrade

#1501 2022-12-06_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.23.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1503 2022-12-06_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1505 2022-12-06_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1504 2022-12-06_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1506 2022-12-06_00-09-41_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.28.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1507 2022-12-06_00-09-41_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.28.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1508 2022-12-06_00-09-41_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.28.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1509 2022-12-06_00-09-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1510 2022-12-06_00-09-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1512 2022-12-06_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.23.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1513 2022-12-06_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.23.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1515 2022-12-06_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1516 2022-12-06_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1517 2022-12-06_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1518 2022-12-07_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.24.bb
Labels: version-upgrade

#1521 2022-12-07_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.24.bb
Labels: version-upgrade

#1520 2022-12-07_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.24.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1523 2022-12-07_00-09-27_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.1.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
Labels: version-upgrade

#1524 2022-12-07_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1522 2022-12-07_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.24.bb
Labels: version-upgrade

#1526 2022-12-07_00-09-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1528 2022-12-07_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.24.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1519 2022-12-07_00-09-27_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: version-upgrade

#1529 2022-12-07_00-09-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1533 2022-12-07_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1535 2022-12-07_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.24.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1531 2022-12-07_00-09-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.24.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1534 2022-12-07_00-09-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1536 2022-12-07_00-09-27_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1539 2022-12-08_00-09-51_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.30.bb
Labels: version-upgrade

#1543 2022-12-08_00-09-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.25.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1545 2022-12-08_00-09-51_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.30.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1549 2022-12-08_00-09-51_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1553 2022-12-08_00-09-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.25.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1554 2022-12-08_00-09-51_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1550 2022-12-08_00-09-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.25.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1544 2022-12-08_00-09-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.25.bb
Labels: version-upgrade

#1547 2022-12-08_00-09-51_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.30.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1556 2022-12-08_00-09-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1557 2022-12-08_00-09-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1558 2022-12-08_00-09-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.25.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1542 2022-12-08_00-09-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.25.bb
Labels: version-upgrade

#1559 2022-12-08_00-09-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.25.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1560 2022-12-08_00-09-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1561 2022-12-08_00-09-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1566 2022-12-09_00-10-32_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.14.bb
Labels: version-upgrade

#1574 2022-12-09_00-10-32_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1573 2022-12-09_00-10-32_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1568 2022-12-09_00-10-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.1.bb
Labels: version-upgrade

#1570 2022-12-09_00-10-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.26.bb
Labels: version-upgrade

#1567 2022-12-09_00-10-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.26.bb
Labels: version-upgrade

#1571 2022-12-09_00-10-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.26.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1575 2022-12-09_00-10-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1576 2022-12-09_00-10-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1578 2022-12-09_00-10-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.26.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1582 2022-12-09_00-10-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.26.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1577 2022-12-09_00-10-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1581 2022-12-09_00-10-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.26.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1585 2022-12-09_00-10-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.26.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1586 2022-12-09_00-10-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.26.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1579 2022-12-09_00-10-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.26.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1584 2022-12-09_00-10-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.26.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1583 2022-12-09_00-10-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.26.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1580 2022-12-09_00-10-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.26.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1569 2022-12-09_00-10-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.26.bb
Labels: version-upgrade

#1588 2022-12-09_00-10-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.26.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1589 2022-12-09_00-10-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.26.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1587 2022-12-09_00-10-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.26.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1590 2022-12-10_00-09-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.27.bb
Labels: version-upgrade

#1592 2022-12-10_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.27.bb
Labels: version-upgrade

#1593 2022-12-10_00-09-41_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.1.bb
Labels: version-upgrade

#1594 2022-12-10_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1595 2022-12-10_00-09-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1601 2022-12-10_00-09-41_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1599 2022-12-10_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.27.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1596 2022-12-10_00-09-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1598 2022-12-10_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1600 2022-12-10_00-09-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1603 2022-12-10_00-09-41_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1604 2022-12-10_00-09-41_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1605 2022-12-10_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1606 2022-12-10_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1602 2022-12-10_00-09-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1591 2022-12-10_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.27.bb
Labels: version-upgrade

#1607 2022-12-10_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.27.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1609 2022-12-10_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1608 2022-12-10_00-09-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale
