Repository aws4embeddedlinux/meta-aws, pull requests merged in 2022-11, with the labels that each got.

#974 2022-11-01_00-14-08_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.375.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#971 2022-11-01_00-14-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.26.5.bb
Labels: version-upgrade

#979 2022-11-01_00-14-08_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.5.bb
Labels: version-upgrade, auto, backport, dunfell

#976 2022-11-01_00-14-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.28.5.bb
Labels: version-upgrade, auto, backport, kirkstone

#978 2022-11-01_00-14-08_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.5.bb
Labels: version-upgrade, auto, backport, kirkstone

#977 2022-11-01_00-14-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.28.5.bb
Labels: version-upgrade, auto, backport, dunfell

#982 2022-11-02_00-11-43_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.183.0.bb
Labels: version-upgrade

#980 2022-11-02_00-11-43_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.0.bb
Labels: version-upgrade

#985 2022-11-02_00-11-43_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.0.bb
Labels: version-upgrade

#984 2022-11-02_00-11-43_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.24.bb
Labels: version-upgrade

#981 2022-11-02_00-11-43_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.376.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#983 2022-11-02_00-11-43_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.0.bb
Labels: version-upgrade

#987 2022-11-02_00-11-43_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.183.0.bb
Labels: version-upgrade, auto, backport, dunfell

#986 2022-11-02_00-11-43_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.183.0.bb
Labels: version-upgrade, auto, backport, kirkstone

#988 2022-11-02_00-11-43_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.0.bb
Labels: version-upgrade, auto, backport, kirkstone

#990 2022-11-02_00-11-43_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.24.bb
Labels: version-upgrade, auto, backport, kirkstone

#989 2022-11-02_00-11-43_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.0.bb
Labels: version-upgrade, auto, backport, dunfell

#991 2022-11-02_00-11-43_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.24.bb
Labels: version-upgrade, auto, backport, dunfell

#998 2022-11-03_00-12-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.1.bb
Labels: version-upgrade

#996 2022-11-03_00-12-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.377.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1001 Update auto-approve-and-enable-auto-merge.yml
  .github/workflows/auto-approve-and-enable-auto-merge.yml
Labels: auto-integrate

#994 2022-11-03_00-12-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.1.bb
Labels: version-upgrade

#997 2022-11-03_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.1.bb
Labels: version-upgrade

#1002 2022-11-03_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1004 2022-11-03_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1003 2022-11-03_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1005 aws-crt-python: version upgrade 0.15.1 -> 0.15.2, remove obs. patch
  recipes-sdk/aws-crt-python/aws-crt-python_0.15.2.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
  recipes-sdk/aws-crt-python/files/0002-disable-building-of-depending-libs.patch
Labels: auto-integrate

#1011 2022-11-04_00-13-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.2.bb
Labels: version-upgrade

#1008 2022-11-04_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.2.bb
Labels: version-upgrade

#1012 2022-11-04_00-13-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.378.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1010 2022-11-04_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.10.bb
Labels: version-upgrade

#1009 2022-11-04_00-13-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.2.bb
Labels: version-upgrade

#1015 2022-11-04_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1016 2022-11-04_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1018 2022-11-04_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1014 2022-11-04_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1017 2022-11-04_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.10.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1029 2022-11-05_00-11-17_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.27.bb
Labels: version-upgrade

#1030 2022-11-05_00-11-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.3.bb
Labels: version-upgrade

#1023 2022-11-05_00-11-17_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.6.bb
Labels: version-upgrade

#1031 2022-11-05_00-11-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.379.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1026 2022-11-05_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.11.bb
Labels: version-upgrade

#1024 2022-11-05_00-11-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.3.bb
Labels: version-upgrade

#1035 2022-11-05_00-11-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1037 2022-11-05_00-11-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1038 2022-11-05_00-11-17_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1039 2022-11-05_00-11-17_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1046 2022-11-05_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1040 2022-11-05_00-11-17_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1045 2022-11-05_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1042 2022-11-05_00-11-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.379.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1047 2022-11-05_00-11-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1048 2022-11-05_00-11-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1049 2022-11-05_00-11-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1044 2022-11-05_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1022 2022-11-05_00-11-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.3.bb
Labels: version-upgrade

#1050 2022-11-05_00-11-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1051 2022-11-05_00-11-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1052 2022-11-05_00-11-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1025 2022-11-05_00-11-17_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.13.bb
Labels: version-upgrade

#1027 2022-11-05_00-11-17_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.5.bb
Labels: version-upgrade

#1056 2022-11-05_00-11-17_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1041 2022-11-05_00-11-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.9.379.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1053 2022-11-05_00-11-17_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1055 2022-11-05_00-11-17_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1057 2022-11-05_00-11-17_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1058 2022-11-05_00-11-17_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1054 2022-11-05_00-11-17_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.7.13.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1028 2022-11-05_00-11-17_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.7.bb
Labels: version-upgrade

#1059 2022-11-05_00-11-17_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1060 2022-11-05_00-11-17_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1061 2022-11-05_00-11-17_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1062 2022-11-07_00-13-37_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.12.bb
Labels: version-upgrade

#1065 2022-11-07_00-13-37_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1063 2022-11-07_00-13-37_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1064 2022-11-07_00-13-37_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.12.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1073 2022-11-08_00-12-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.4.bb
Labels: version-upgrade

#1071 2022-11-08_00-12-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.1.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1072 2022-11-08_00-12-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.4.bb
Labels: version-upgrade

#1078 2022-11-08_00-12-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.4.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1075 2022-11-08_00-12-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.4.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1081 2022-11-08_00-12-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.1.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1077 2022-11-08_00-12-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1086 2022-11-08_00-12-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1080 2022-11-08_00-12-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1076 2022-11-08_00-12-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1085 2022-11-08_00-12-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1083 2022-11-08_00-12-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.1.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1079 2022-11-08_00-12-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1092 2022-11-09_00-12-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.5.bb
Labels: version-upgrade

#1091 2022-11-09_00-12-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.2.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1094 2022-11-09_00-12-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.5.bb
Labels: version-upgrade

#1093 2022-11-09_00-12-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.5.bb
Labels: version-upgrade

#1096 2022-11-09_00-12-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1099 2022-11-09_00-12-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.2.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1102 2022-11-09_00-12-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1104 2022-11-09_00-12-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1098 2022-11-09_00-12-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.2.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1097 2022-11-09_00-12-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1095 2022-11-09_00-12-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1103 2022-11-09_00-12-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1105 2022-11-09_00-12-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1101 2022-11-09_00-12-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1106 2022-11-09_00-12-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1109 2022-11-10_00-11-43_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.8.bb
Labels: version-upgrade

#1112 2022-11-10_00-11-43_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.3.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1110 2022-11-10_00-11-43_master-next_aws-c-compression
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.16.bb
Labels: version-upgrade

#1116 2022-11-10_00-11-43_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.6.bb
Labels: version-upgrade

#1121 2022-11-10_00-11-43_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.8.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1114 2022-11-10_00-11-43_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.13.bb
Labels: version-upgrade

#1122 2022-11-10_00-11-43_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.3.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1125 2022-11-10_00-11-43_master-next_aws-c-compression
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1128 2022-11-10_00-11-43_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1132 2022-11-10_00-11-43_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.13.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1124 2022-11-10_00-11-43_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.3.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1126 2022-11-10_00-11-43_master-next_aws-c-compression
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1120 2022-11-10_00-11-43_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1129 2022-11-10_00-11-43_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1123 2022-11-10_00-11-43_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.3.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1133 2022-11-10_00-11-43_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1127 2022-11-10_00-11-43_master-next_aws-c-compression
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1131 2022-11-10_00-11-43_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.18.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1134 2022-11-11_00-12-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.7.bb
Labels: version-upgrade

#1137 2022-11-11_00-12-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.20.bb
Labels: version-upgrade

#1136 2022-11-11_00-12-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.5.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1138 2022-11-11_00-12-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.9.bb
Labels: version-upgrade

#1139 2022-11-11_00-12-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.7.bb
Labels: version-upgrade

#1135 2022-11-11_00-12-29_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.27.bb
Labels: version-upgrade

#1141 2022-11-11_00-12-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.7.bb
Labels: version-upgrade

#1140 2022-11-11_00-12-29_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.15.3.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
Labels: version-upgrade

#1145 2022-11-11_00-12-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.20.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1148 2022-11-11_00-12-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.5.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1144 2022-11-11_00-12-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1154 2022-11-11_00-12-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1151 2022-11-11_00-12-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.9.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1157 2022-11-11_00-12-29_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.27.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1160 2022-11-11_00-12-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1146 2022-11-11_00-12-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1158 2022-11-11_00-12-29_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1155 2022-11-11_00-12-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1142 2022-11-11_00-12-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1149 2022-11-11_00-12-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.5.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1152 2022-11-11_00-12-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.9.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1150 2022-11-11_00-12-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1161 2022-11-11_00-12-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1143 2022-11-11_00-12-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1153 2022-11-11_00-12-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1159 2022-11-11_00-12-29_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.6.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1162 2022-11-11_00-12-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1147 2022-11-11_00-12-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.5.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created
