Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-08, with the labels that each got.

#4806 2023-08-01_00-17-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.16.bb
Labels: version-upgrade

#4809 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.26.0.bb
Labels: version-upgrade

#4810 2023-08-01_00-17-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.16.bb
Labels: version-upgrade

#4812 2023-08-01_00-17-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4813 2023-08-01_00-17-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4811 2023-08-01_00-17-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.16.bb
Labels: version-upgrade

#4816 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.26.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4817 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.26.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4808 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.17.0.bb
Labels: version-upgrade

#4819 2023-08-01_00-17-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4820 2023-08-01_00-17-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4821 2023-08-01_00-17-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4814 2023-08-01_00-17-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4818 2023-08-01_00-17-32_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.48.bb
Labels: version-upgrade

#4823 2023-08-01_00-17-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4822 2023-08-01_00-17-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4824 2023-08-01_00-17-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4825 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.17.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4826 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.17.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4827 2023-08-01_00-17-32_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.17.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4807 2023-08-01_00-17-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.131.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4828 2023-08-01_00-17-32_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.48.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4830 2023-08-01_00-17-32_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.48.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4829 2023-08-01_00-17-32_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.48.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4831 2023-08-01_00-17-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.131.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4833 2023-08-01_00-17-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.131.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4832 2023-08-01_00-17-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.131.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4834 2023-08-02_00-15-37_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.17.bb
Labels: version-upgrade

#4836 2023-08-02_00-15-37_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.13.0.bb
Labels: version-upgrade

#4835 2023-08-02_00-15-37_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.17.bb
Labels: version-upgrade

#4839 2023-08-02_00-15-37_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4840 2023-08-02_00-15-37_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4838 2023-08-02_00-15-37_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.17.bb
Labels: version-upgrade

#4844 2023-08-02_00-15-37_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.13.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4847 2023-08-02_00-15-37_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4849 2023-08-02_00-15-37_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4850 2023-08-02_00-15-37_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4837 2023-08-02_00-15-37_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.132.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4842 2023-08-02_00-15-37_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.13.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4841 2023-08-02_00-15-37_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4846 2023-08-02_00-15-37_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4848 2023-08-02_00-15-37_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4851 2023-08-02_00-15-37_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.132.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4852 2023-08-02_00-15-37_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.132.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4853 2023-08-02_00-15-37_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.132.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4857 2023-08-03_00-14-30_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
Labels: version-upgrade

#4860 2023-08-03_00-14-30_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4856 2023-08-03_00-14-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.18.bb
Labels: version-upgrade

#4858 2023-08-03_00-14-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.18.bb
Labels: version-upgrade

#4859 2023-08-03_00-14-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.18.bb
Labels: version-upgrade

#4863 2023-08-03_00-14-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.18.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4864 2023-08-03_00-14-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.18.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4867 2023-08-03_00-14-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.18.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4854 2023-08-03_00-14-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.133.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4862 2023-08-03_00-14-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4866 2023-08-03_00-14-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4869 2023-08-03_00-14-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4861 2023-08-03_00-14-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4865 2023-08-03_00-14-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4868 2023-08-03_00-14-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4872 2023-08-03_00-14-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.133.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4871 2023-08-03_00-14-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.133.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4870 2023-08-03_00-14-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.133.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4873 2023-08-04_00-14-00_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.2.bb
Labels: version-upgrade

#4874 2023-08-04_00-14-00_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.19.bb
Labels: version-upgrade

#4879 2023-08-04_00-14-00_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.19.bb
Labels: version-upgrade

#4880 2023-08-04_00-14-00_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4881 2023-08-04_00-14-00_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.19.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4876 2023-08-04_00-14-00_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4877 2023-08-04_00-14-00_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4878 2023-08-04_00-14-00_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4882 2023-08-04_00-14-00_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4883 2023-08-04_00-14-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.19.bb
Labels: version-upgrade

#4884 2023-08-04_00-14-00_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.31.bb
Labels: version-upgrade

#4885 2023-08-04_00-14-00_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4886 2023-08-04_00-14-00_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.19.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4887 2023-08-04_00-14-00_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4889 2023-08-04_00-14-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4890 2023-08-04_00-14-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4891 2023-08-04_00-14-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.19.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4892 2023-08-04_00-14-00_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.31.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4893 2023-08-04_00-14-00_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4888 2023-08-04_00-14-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.134.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4895 2023-08-04_00-14-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.134.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4897 2023-08-04_00-14-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.134.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4896 2023-08-04_00-14-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.134.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4901 2023-08-08_00-13-50_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.16.bb
Labels: version-upgrade

#4898 2023-08-08_00-13-50_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.21.bb
Labels: version-upgrade

#4902 2023-08-08_00-13-50_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.21.bb
Labels: version-upgrade

#4903 2023-08-08_00-13-50_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.21.bb
Labels: version-upgrade

#4906 2023-08-08_00-13-50_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.3.bb
Labels: version-upgrade

#4904 2023-08-08_00-13-50_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.136.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4913 2023-08-08_00-13-50_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4917 2023-08-08_00-13-50_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4909 2023-08-08_00-13-50_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.22.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4912 2023-08-08_00-13-50_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.27.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4919 2023-08-08_00-13-50_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4924 2023-08-08_00-13-50_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4925 2023-08-08_00-13-50_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4911 2023-08-08_00-13-50_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.27.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4923 2023-08-08_00-13-50_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4928 2023-08-08_00-13-50_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.136.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4926 2023-08-08_00-13-50_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4907 2023-08-08_00-13-50_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.22.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4914 2023-08-08_00-13-50_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4910 2023-08-08_00-13-50_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4908 2023-08-08_00-13-50_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.22.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4915 2023-08-08_00-13-50_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.27.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4927 2023-08-08_00-13-50_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4922 2023-08-08_00-13-50_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4916 2023-08-08_00-13-50_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4918 2023-08-08_00-13-50_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4921 2023-08-08_00-13-50_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4929 2023-08-08_00-13-50_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.136.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4930 2023-08-08_00-13-50_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.136.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4931 2023-08-09_00-14-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.22.bb
Labels: version-upgrade

#4932 2023-08-09_00-14-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.22.bb
Labels: version-upgrade

#4933 2023-08-09_00-14-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.22.bb
Labels: version-upgrade

#4934 2023-08-09_00-14-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4935 2023-08-09_00-14-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4936 2023-08-09_00-14-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4938 2023-08-09_00-14-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4939 2023-08-09_00-14-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4940 2023-08-09_00-14-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4942 2023-08-09_00-14-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.22.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4944 2023-08-09_00-14-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4943 2023-08-09_00-14-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4937 2023-08-09_00-14-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.137.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4947 2023-08-09_00-14-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.137.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4946 2023-08-09_00-14-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.137.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4945 2023-08-09_00-14-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.137.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4948 2023-08-10_00-14-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.23.bb
Labels: version-upgrade

#4949 2023-08-10_00-14-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.23.bb
Labels: version-upgrade

#4953 2023-08-10_00-14-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4955 2023-08-10_00-14-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4954 2023-08-10_00-14-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4952 2023-08-10_00-14-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.23.bb
Labels: version-upgrade

#4956 2023-08-10_00-14-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4958 2023-08-10_00-14-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4957 2023-08-10_00-14-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4950 2023-08-10_00-14-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.138.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4960 2023-08-10_00-14-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4959 2023-08-10_00-14-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4961 2023-08-10_00-14-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4962 2023-08-10_00-14-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.138.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4964 2023-08-10_00-14-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.138.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4963 2023-08-10_00-14-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.138.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4965 Thomas roos patch 1
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.0.7.bb
Labels: backport

#4966 2023-08-11_00-13-53_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.3.bb
Labels: version-upgrade

#4968 2023-08-11_00-13-53_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.24.bb
Labels: version-upgrade
