Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-04, with the labels that each got.

#3147 aws-c-common: upgrade 0.8.14 -> 0.8.15, fix ptest
  recipes-sdk/aws-c-common/aws-c-common_0.8.15.bb
  recipes-sdk/aws-c-common/files/run-ptest
Labels: auto-backport

#3146 greengrass-bin: replace WORKDIR with S
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.4.bb
Labels: auto-backport

#3154 greengrass-bin: replace WORKDIR with S
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#3153 greengrass-bin: replace WORKDIR with S
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#3149 aws-c-common: upgrade 0.8.14 -> 0.8.15, fix ptest
  recipes-sdk/aws-c-common/aws-c-common_0.8.15.bb
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#3152 greengrass-bin: replace WORKDIR with S
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#3151 aws-c-common: upgrade 0.8.14 -> 0.8.15, fix ptest
  recipes-sdk/aws-c-common/aws-c-common_0.8.15.bb
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#3161 2023-04-04_00-13-11_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: version-upgrade

#3159 2023-04-04_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.105.bb
Labels: version-upgrade

#3162 2023-04-04_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.105.bb
Labels: version-upgrade

#3158 2023-04-04_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.105.bb
Labels: version-upgrade

#3164 2023-04-04_00-13-11_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3171 2023-04-04_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.105.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3163 2023-04-04_00-13-11_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3165 2023-04-04_00-13-11_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3169 2023-04-04_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3172 2023-04-04_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.105.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3167 2023-04-04_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3174 2023-04-04_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3160 2023-04-04_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.51.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3177 2023-04-04_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.51.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3175 2023-04-04_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.51.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3176 2023-04-04_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.51.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3179 2023-04-05_00-12-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.8.bb
Labels: version-upgrade

#3180 2023-04-05_00-12-31_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.42.bb
Labels: version-upgrade

#3178 2023-04-05_00-12-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.106.bb
Labels: version-upgrade

#3182 2023-04-05_00-12-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.8.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3183 2023-04-05_00-12-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3189 2023-04-05_00-12-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.106.bb
Labels: version-upgrade

#3190 2023-04-05_00-12-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.106.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3187 2023-04-05_00-12-31_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.42.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3192 2023-04-05_00-12-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.106.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3195 2023-04-05_00-12-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.106.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3193 2023-04-05_00-12-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.106.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3181 2023-04-05_00-12-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.106.bb
Labels: version-upgrade

#3196 2023-04-05_00-12-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.106.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3197 2023-04-05_00-12-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.106.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3184 2023-04-05_00-12-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3186 2023-04-05_00-12-31_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.42.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3191 2023-04-05_00-12-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.106.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3194 2023-04-05_00-12-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.106.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3185 2023-04-05_00-12-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.52.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3198 2023-04-05_00-12-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.106.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3199 2023-04-05_00-12-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.52.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3201 2023-04-05_00-12-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.52.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3200 2023-04-05_00-12-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.52.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3203 2023-04-06_00-12-47_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.815.0.bb
Labels: version-upgrade

#3202 2023-04-06_00-12-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.107.bb
Labels: version-upgrade

#3204 2023-04-06_00-12-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.107.bb
Labels: version-upgrade

#3205 2023-04-06_00-12-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.107.bb
Labels: version-upgrade

#3207 2023-04-06_00-12-47_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.815.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3206 2023-04-06_00-12-47_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.815.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3208 2023-04-06_00-12-47_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.815.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3209 2023-04-06_00-12-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3211 2023-04-06_00-12-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.107.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3214 2023-04-06_00-12-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.107.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3215 2023-04-06_00-12-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.107.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3213 2023-04-06_00-12-47_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3210 2023-04-06_00-12-47_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.107.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3218 2023-04-06_00-12-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3216 2023-04-06_00-12-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.107.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3217 2023-04-06_00-12-47_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.107.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3212 2023-04-06_00-12-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.53.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3219 2023-04-06_00-12-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.53.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3220 2023-04-06_00-12-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.53.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3221 2023-04-06_00-12-47_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.53.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3223 2023-04-07_00-12-30_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.7.0.bb
Labels: version-upgrade

#3226 2023-04-07_00-12-30_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.7.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3228 2023-04-07_00-12-30_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.7.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3222 2023-04-07_00-12-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.108.bb
Labels: version-upgrade

#3227 2023-04-07_00-12-30_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.7.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3229 2023-04-07_00-12-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.108.bb
Labels: version-upgrade

#3230 2023-04-07_00-12-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.108.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3232 2023-04-07_00-12-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.108.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3231 2023-04-07_00-12-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.108.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3225 2023-04-07_00-12-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.108.bb
Labels: version-upgrade

#3233 2023-04-07_00-12-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.108.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3235 2023-04-07_00-12-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.108.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3236 2023-04-07_00-12-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.108.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3234 2023-04-07_00-12-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.108.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3238 2023-04-07_00-12-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.108.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3224 2023-04-07_00-12-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.54.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3241 2023-04-07_00-12-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.54.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3240 2023-04-07_00-12-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.54.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3239 2023-04-07_00-12-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.54.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3243 2023-04-11_00-13-11_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.8.bb
Labels: version-upgrade

#3244 2023-04-11_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.110.bb
Labels: version-upgrade

#3248 2023-04-11_00-13-11_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3250 2023-04-11_00-13-11_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3245 2023-04-11_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.110.bb
Labels: version-upgrade

#3247 2023-04-11_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.110.bb
Labels: version-upgrade

#3249 2023-04-11_00-13-11_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.8.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3253 2023-04-11_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.110.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3257 2023-04-11_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.110.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3256 2023-04-11_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.110.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3251 2023-04-11_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.110.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3246 2023-04-11_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.56.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3252 2023-04-11_00-13-11_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.110.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3258 2023-04-11_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.110.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3259 2023-04-11_00-13-11_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.110.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3255 2023-04-11_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.110.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3254 2023-04-11_00-13-11_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.110.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3260 2023-04-11_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.56.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3262 2023-04-11_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.56.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3261 2023-04-11_00-13-11_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.56.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3270 2023-04-12_00-12-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.111.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3272 2023-04-12_00-12-39_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.8.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3279 2023-04-12_00-12-39_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3280 2023-04-12_00-12-39_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.20.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3277 2023-04-12_00-12-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.111.bb
Labels: version-upgrade

#3282 2023-04-12_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.111.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3274 2023-04-12_00-12-39_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.8.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3285 2023-04-12_00-12-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.111.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3269 2023-04-12_00-12-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.111.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3278 2023-04-12_00-12-39_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3287 2023-04-12_00-12-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.111.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3267 2023-04-12_00-12-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.57.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3283 2023-04-12_00-12-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.111.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3286 2023-04-12_00-12-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.111.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3290 2023-04-12_00-12-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.57.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3288 2023-04-12_00-12-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.57.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3289 2023-04-12_00-12-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.57.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3276 2023-04-12_00-12-39_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.7.bb
Labels: version-upgrade

#3292 2023-04-12_00-12-39_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3293 2023-04-12_00-12-39_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3294 2023-04-12_00-12-39_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3271 2023-04-12_00-12-39_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.10.bb
Labels: version-upgrade

#3295 2023-04-12_00-12-39_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3297 2023-04-12_00-12-39_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.10.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3296 2023-04-12_00-12-39_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3298 greengrass-bin: do not hard RDEPEND on ntp
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#3299 greengrass-bin: do not hard RDEPEND on ntp
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.5.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#3301 2023 04 12 firecracker bin ptest
  recipes-containers/firecracker-bin/firecracker-bin/run-ptest
  recipes-containers/firecracker-bin/firecracker-bin_1.3.1.bb
  recipes-containers/firecracker-bin/firecracker-microvm-bin.inc
  recipes-containers/firecracker-bin/jailer-bin/run-ptest
  recipes-containers/firecracker-bin/jailer-bin_1.3.1.bb
Labels: auto-integrate, auto-backport

#3308 2023-04-13_00-12-12_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.112.bb
Labels: version-upgrade

#3311 2023-04-13_00-12-12_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.112.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3313 2023-04-13_00-12-12_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.112.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3312 2023-04-13_00-12-12_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.112.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3310 2023-04-13_00-12-12_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.112.bb
Labels: version-upgrade

#3315 2023-04-13_00-12-12_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.16.bb
Labels: version-upgrade

#3317 2023-04-13_00-12-12_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.112.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3320 2023-04-13_00-12-12_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.112.bb
Labels: version-upgrade

#3318 2023-04-13_00-12-12_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.112.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3321 2023-04-13_00-12-12_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3319 2023-04-13_00-12-12_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.112.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3324 2023-04-13_00-12-12_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.9.bb
Labels: version-upgrade

#3325 2023-04-13_00-12-12_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.112.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3322 2023-04-13_00-12-12_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3327 2023-04-13_00-12-12_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.112.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3328 2023-04-13_00-12-12_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.21.bb
Labels: version-upgrade

#3329 2023-04-13_00-12-12_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created
