Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-05, with the labels that each got.

#3558 2023-05-02_00-13-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.124.bb
Labels: version-upgrade

#3559 2023-05-02_00-13-06_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.11.bb
Labels: version-upgrade

#3563 2023-05-02_00-13-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.124.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3562 2023-05-02_00-13-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.124.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3560 2023-05-02_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.124.bb
Labels: version-upgrade

#3561 2023-05-02_00-13-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.124.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3569 2023-05-02_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.124.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3571 2023-05-02_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.124.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3565 2023-05-02_00-13-06_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3566 2023-05-02_00-13-06_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3567 2023-05-02_00-13-06_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3568 2023-05-02_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.1.bb
Labels: version-upgrade

#3570 2023-05-02_00-13-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.124.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3574 2023-05-02_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3575 2023-05-02_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3576 2023-05-02_00-13-06_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3577 2023-05-02_00-13-06_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.0.bb
Labels: version-upgrade

#3573 2023-05-02_00-13-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.124.bb
Labels: version-upgrade

#3578 2023-05-02_00-13-06_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3579 2023-05-02_00-13-06_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3580 2023-05-02_00-13-06_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3581 2023-05-02_00-13-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.124.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3582 2023-05-02_00-13-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.124.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3583 2023-05-02_00-13-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.124.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3564 2023-05-02_00-13-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.70.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3585 2023-05-02_00-13-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.70.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3584 2023-05-02_00-13-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.70.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3586 2023-05-02_00-13-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.70.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3587 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.0.bb
Labels: version-upgrade

#3588 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.23.1.bb
Labels: version-upgrade

#3593 2023-05-03_00-13-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.125.bb
Labels: version-upgrade

#3589 2023-05-03_00-13-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.125.bb
Labels: version-upgrade

#3597 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.23.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3591 2023-05-03_00-13-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.125.bb
Labels: version-upgrade

#3594 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3595 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3596 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3598 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.23.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3599 2023-05-03_00-13-02_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.23.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3600 2023-05-03_00-13-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.125.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3601 2023-05-03_00-13-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.125.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3602 2023-05-03_00-13-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.125.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3603 2023-05-03_00-13-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.125.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3606 2023-05-03_00-13-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.125.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3608 2023-05-03_00-13-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.125.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3605 2023-05-03_00-13-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.125.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3590 2023-05-03_00-13-02_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.71.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3609 2023-05-03_00-13-02_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.71.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3611 2023-05-03_00-13-02_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.71.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3610 2023-05-03_00-13-02_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.71.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3613 2023-05-04_00-12-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.126.bb
Labels: version-upgrade

#3612 2023-05-04_00-12-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.126.bb
Labels: version-upgrade

#3615 2023-05-04_00-12-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.126.bb
Labels: version-upgrade

#3619 2023-05-04_00-12-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.126.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3622 2023-05-04_00-12-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.126.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3616 2023-05-04_00-12-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.126.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3621 2023-05-04_00-12-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.126.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3620 2023-05-04_00-12-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.126.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3618 2023-05-04_00-12-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.126.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3614 2023-05-04_00-12-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.72.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3625 2023-05-04_00-12-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.72.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3624 2023-05-04_00-12-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.72.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3623 2023-05-04_00-12-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.72.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3607 2023-05-03_00-13-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.125.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3604 2023-05-03_00-13-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.125.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3628 aws-crt-python: upgrade 0.16.15 -> 0.16.16, readd shared patch
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.16.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: auto-integrate, auto-backport

#3633 2023-05-05_00-12-45_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.6.1.bb
Labels: version-upgrade

#3631 2023-05-05_00-12-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.127.bb
Labels: version-upgrade

#3634 2023-05-05_00-12-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.127.bb
Labels: version-upgrade

#3635 2023-05-05_00-12-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.127.bb
Labels: version-upgrade

#3637 2023-05-05_00-12-45_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.6.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3643 2023-05-05_00-12-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.127.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3636 2023-05-05_00-12-45_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.6.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3639 2023-05-05_00-12-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.127.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3641 2023-05-05_00-12-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.127.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3644 2023-05-05_00-12-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.127.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3632 2023-05-05_00-12-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.73.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3638 2023-05-05_00-12-45_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.6.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3640 2023-05-05_00-12-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.127.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3642 2023-05-05_00-12-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.127.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3645 2023-05-05_00-12-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.73.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3646 2023-05-05_00-12-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.73.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3647 2023-05-05_00-12-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.73.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#3655 2023-05-09_00-13-21_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.923.0.bb
Labels: version-upgrade

#3661 2023-05-09_00-13-21_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.923.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3654 2023-05-09_00-13-21_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.130.bb
Labels: version-upgrade

#3657 2023-05-09_00-13-21_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.17.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#3662 2023-05-09_00-13-21_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.1.bb
Labels: version-upgrade

#3660 2023-05-09_00-13-21_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.923.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3663 2023-05-09_00-13-21_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.27.bb
Labels: version-upgrade

#3656 2023-05-09_00-13-21_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.130.bb
Labels: version-upgrade

#3666 2023-05-09_00-13-21_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.130.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3665 2023-05-09_00-13-21_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.130.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3669 2023-05-09_00-13-21_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3670 2023-05-09_00-13-21_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3674 2023-05-09_00-13-21_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.27.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3675 2023-05-09_00-13-21_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3673 2023-05-09_00-13-21_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.130.bb
Labels: version-upgrade

#3679 2023-05-09_00-13-21_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_08.14.bb
Labels: version-upgrade

#3658 2023-05-09_00-13-21_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.923.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3684 2023-05-09_00-13-21_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_08.14.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3682 2023-05-09_00-13-21_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.130.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3683 2023-05-09_00-13-21_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_08.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3685 2023-05-09_00-13-21_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_08.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3677 2023-05-09_00-13-21_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3664 2023-05-09_00-13-21_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.130.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3668 2023-05-09_00-13-21_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.17.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3671 2023-05-09_00-13-21_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.14.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3681 2023-05-09_00-13-21_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.130.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3678 2023-05-09_00-13-21_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.75.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3690 2023-05-09_00-13-21_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.75.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3689 2023-05-09_00-13-21_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.75.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3688 2023-05-09_00-13-21_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.75.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3693 2023 05 09 master next aws c common
  .github/workflows/auto-backport.yml
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#3697 2023-05-10_00-12-59_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.44.bb
Labels: version-upgrade

#3703 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.0.bb
Labels: version-upgrade

#3700 2023-05-10_00-12-59_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.44.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3701 2023-05-10_00-12-59_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.44.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3702 2023-05-10_00-12-59_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.44.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3698 2023-05-10_00-12-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.131.bb
Labels: version-upgrade

#3705 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.0.bb
Labels: version-upgrade

#3706 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3708 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3707 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3710 2023-05-10_00-12-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.131.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3711 2023-05-10_00-12-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.131.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3712 2023-05-10_00-12-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.131.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3699 2023-05-10_00-12-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.131.bb
Labels: version-upgrade

#3704 2023-05-10_00-12-59_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.131.bb
Labels: version-upgrade

#3714 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3715 2023-05-10_00-12-59_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3709 2023-05-10_00-12-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.76.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3717 2023-05-10_00-12-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.76.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3716 2023-05-10_00-12-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.76.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3718 2023-05-10_00-12-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.76.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3721 2023-05-11_00-13-00_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.132.bb
Labels: version-upgrade

#3720 2023-05-11_00-13-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.132.bb
Labels: version-upgrade

#3722 2023-05-11_00-13-00_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.132.bb
Labels: version-upgrade

#3719 2023-05-11_00-13-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.77.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#3724 2023-05-11_00-13-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.132.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3723 2023-05-11_00-13-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.132.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3725 2023-05-11_00-13-00_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.132.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3726 2023-05-11_00-13-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.77.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3728 2023-05-11_00-13-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.77.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#3727 2023-05-11_00-13-00_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.77.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3729 2023-05-12_00-12-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.133.bb
Labels: version-upgrade

#3731 2023-05-12_00-12-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.133.bb
Labels: version-upgrade

#3732 2023-05-12_00-12-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.133.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#3733 2023-05-12_00-12-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.133.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#3734 2023-05-12_00-12-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.133.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore
