Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-06, with the labels that each got.

#4010 2023-06-01_00-17-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.144.bb
Labels: version-upgrade

#4009 2023-06-01_00-17-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.144.bb
Labels: version-upgrade

#4012 2023-06-01_00-17-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.144.bb
Labels: version-upgrade

#4013 2023-06-01_00-17-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.144.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4015 2023-06-01_00-17-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.144.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4019 2023-06-01_00-17-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.144.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4023 2023-06-01_00-17-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.144.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4021 2023-06-01_00-17-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.144.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4017 2023-06-01_00-17-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.144.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4016 2023-06-01_00-17-55_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.19.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#4020 2023-06-01_00-17-55_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.2.bb
Labels: version-upgrade

#4014 2023-06-01_00-17-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.144.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4018 2023-06-01_00-17-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.144.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4022 2023-06-01_00-17-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.144.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4026 2023-06-01_00-17-55_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4025 2023-06-01_00-17-55_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4027 2023-06-01_00-17-55_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4011 2023-06-01_00-17-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.90.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4024 2023-06-01_00-17-55_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.19.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4029 2023-06-01_00-17-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.90.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4028 2023-06-01_00-17-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.90.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4030 2023-06-01_00-17-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.90.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4031 README.md: fleetwise wording
  README.md
Labels: auto-backport

#4032 README.md: fleetwise wording
  README.md
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4033 README.md: fleetwise wording
  README.md
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4034 README.md: fleetwise wording
  README.md
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4035 firecracker-bin jailer-bin: upgrade 1.3.1 -> 1.3.3
  recipes-containers/firecracker-bin/firecracker-bin_1.3.1.bb
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/firecracker-microvm-bin.inc
  recipes-containers/firecracker-bin/jailer-bin_1.3.1.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: auto-backport

#4036 firecracker-bin jailer-bin: upgrade 1.3.1 -> 1.3.3
  recipes-containers/firecracker-bin/firecracker-bin_1.3.1.bb
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/firecracker-microvm-bin.inc
  recipes-containers/firecracker-bin/jailer-bin_1.3.1.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4037 firecracker-bin jailer-bin: upgrade 1.3.1 -> 1.3.3
  recipes-containers/firecracker-bin/firecracker-bin_1.3.1.bb
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/firecracker-microvm-bin.inc
  recipes-containers/firecracker-bin/jailer-bin_1.3.1.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4038 firecracker-bin jailer-bin: upgrade 1.3.1 -> 1.3.3
  recipes-containers/firecracker-bin/firecracker-bin_1.3.1.bb
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/firecracker-microvm-bin.inc
  recipes-containers/firecracker-bin/jailer-bin_1.3.1.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4039 2023-06-02_00-14-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.145.bb
Labels: version-upgrade

#4040 2023-06-02_00-14-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.145.bb
Labels: version-upgrade

#4045 2023-06-02_00-14-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.145.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4044 2023-06-02_00-14-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.145.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4046 2023-06-02_00-14-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.145.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4042 2023-06-02_00-14-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.91.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4048 2023-06-02_00-14-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.145.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4049 2023-06-02_00-14-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.145.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4043 2023-06-02_00-14-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.145.bb
Labels: version-upgrade

#4047 2023-06-02_00-14-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.145.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4053 2023-06-02_00-14-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.145.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4054 2023-06-02_00-14-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.145.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4055 2023-06-02_00-14-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.145.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4050 2023-06-02_00-14-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.91.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4052 2023-06-02_00-14-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.91.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4051 2023-06-02_00-14-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.91.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4068 2023-06-06_00-14-13_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.16.bb
Labels: version-upgrade

#4072 2023-06-06_00-14-13_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.147.bb
Labels: version-upgrade

#4078 2023-06-06_00-14-13_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4079 2023-06-06_00-14-13_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4067 2023-06-06_00-14-13_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.147.bb
Labels: version-upgrade

#4075 2023-06-06_00-14-13_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.23.bb
Labels: version-upgrade

#4076 2023-06-06_00-14-13_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.147.bb
Labels: version-upgrade

#4077 2023-06-06_00-14-13_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4071 2023-06-06_00-14-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.24.bb
Labels: version-upgrade

#4080 2023-06-06_00-14-13_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.147.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4082 2023-06-06_00-14-13_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.147.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4073 2023-06-06_00-14-13_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1041.0.bb
Labels: version-upgrade

#4083 2023-06-06_00-14-13_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.147.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4088 2023-06-06_00-14-13_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.147.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4086 2023-06-06_00-14-13_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.23.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4089 2023-06-06_00-14-13_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.147.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4091 2023-06-06_00-14-13_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.147.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4093 2023-06-06_00-14-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4094 2023-06-06_00-14-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.24.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4085 2023-06-06_00-14-13_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4087 2023-06-06_00-14-13_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4069 2023-06-06_00-14-13_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4092 2023-06-06_00-14-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4096 2023-06-06_00-14-13_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1041.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4095 2023-06-06_00-14-13_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1041.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4081 2023-06-06_00-14-13_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.147.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4084 2023-06-06_00-14-13_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.147.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4090 2023-06-06_00-14-13_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.147.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4098 2023-06-06_00-14-13_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4099 2023-06-06_00-14-13_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4097 2023-06-06_00-14-13_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4100 aws-c-common: improve ptest by running parallel ctest
  recipes-sdk/aws-c-common/files/run-ptest
Labels: auto-backport

#4101 aws-c-common: improve ptest by running parallel ctest
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4103 aws-c-common: improve ptest by running parallel ctest
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4102 aws-c-common: improve ptest by running parallel ctest
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4074 2023-06-06_00-14-13_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.10.bb
Labels: version-upgrade

#4070 2023-06-06_00-14-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.5.bb
Labels: version-upgrade

#4106 2023-06-06_00-14-13_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4109 2023-06-06_00-14-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4108 2023-06-06_00-14-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4107 2023-06-06_00-14-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4111 aws-sdk-cpp: improve ptest
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/ptest_result.py
  recipes-sdk/aws-sdk-cpp/files/run-ptest
Labels: auto-backport

#4113 aws-sdk-cpp: improve ptest
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/ptest_result.py
  recipes-sdk/aws-sdk-cpp/files/run-ptest
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4114 aws-sdk-cpp: improve ptest
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/ptest_result.py
  recipes-sdk/aws-sdk-cpp/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4115 aws-sdk-cpp: improve ptest
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.93.bb
  recipes-sdk/aws-sdk-cpp/files/ptest_result.py
  recipes-sdk/aws-sdk-cpp/files/run-ptest
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4118 2023-06-07_00-16-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.148.bb
Labels: version-upgrade

#4119 2023-06-07_00-16-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.148.bb
Labels: version-upgrade

#4117 2023-06-07_00-16-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.148.bb
Labels: version-upgrade

#4122 2023-06-07_00-16-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.148.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4126 2023-06-07_00-16-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.148.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4129 2023-06-07_00-16-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.148.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4125 2023-06-07_00-16-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.148.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4121 2023-06-07_00-16-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.148.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4124 2023-06-07_00-16-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.148.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4127 2023-06-07_00-16-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.148.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4123 2023-06-07_00-16-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.148.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4130 2023-06-07_00-16-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.94.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4132 2023-06-07_00-16-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.94.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4131 2023-06-07_00-16-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.94.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4134 2023-06-08_00-15-35_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.13.bb
Labels: version-upgrade

#4138 2023-06-08_00-15-35_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4139 2023-06-08_00-15-35_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.13.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4140 2023-06-08_00-15-35_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4135 2023-06-08_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.149.bb
Labels: version-upgrade

#4141 2023-06-08_00-15-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.149.bb
Labels: version-upgrade

#4142 2023-06-08_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.149.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4143 2023-06-08_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.149.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4144 2023-06-08_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.149.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4145 2023-06-08_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-boto3_1.26.149.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4147 2023-06-08_00-15-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.149.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4148 2023-06-08_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-boto3_1.26.149.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4137 2023-06-08_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.95.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4150 2023-06-08_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.95.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4151 2023-06-08_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.95.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4149 2023-06-08_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.95.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4152 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.3.bb
Labels: version-upgrade

#4153 2023-06-09_00-14-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.150.bb
Labels: version-upgrade

#4155 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4154 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.3.bb
Labels: version-upgrade

#4156 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4157 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.15.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4158 2023-06-09_00-14-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.150.bb
Labels: version-upgrade

#4159 2023-06-09_00-14-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.150.bb
Labels: version-upgrade

#4160 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4161 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4162 2023-06-09_00-14-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.24.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4164 2023-06-09_00-14-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.150.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4165 2023-06-09_00-14-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.150.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4166 2023-06-09_00-14-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.150.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4167 2023-06-09_00-14-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.150.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4168 2023-06-09_00-14-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.150.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4169 2023-06-09_00-14-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.150.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4163 2023-06-09_00-14-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.96.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4172 2023-06-09_00-14-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.96.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4170 2023-06-09_00-14-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.96.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4171 2023-06-09_00-14-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.96.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4173 aws-iot-device-client: disable recipe because of pending issues
  recipes-iot/aws-iot-device-client/README.md
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: auto-backport

#4174 aws-iot-device-client: disable recipe because of pending issues
  recipes-iot/aws-iot-device-client/README.md
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4177 amazon-kvs-producer-pic: change ptest mechanism
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/ptest_result.py
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/run-ptest
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
Labels: auto-backport

#4178 amazon-kvs-producer-pic: change ptest mechanism
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/ptest_result.py
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/run-ptest
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4179 amazon-kvs-producer-pic: change ptest mechanism
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/ptest_result.py
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/run-ptest
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#4180 amazon-kvs-producer-pic: change ptest mechanism
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/ptest_result.py
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic/run-ptest
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4181 2023-06-13_00-15-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.152.bb
Labels: version-upgrade

#4182 2023-06-13_00-15-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.152.bb
Labels: version-upgrade
