Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-01, with the labels that each got.

#1822 2022-12-28_00-09-38_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.38.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1888 aws-c-iot: upgrade 0.1.8 -> 0.1.9, add ptest, oelint-adv
  recipes-sdk/aws-c-iot/aws-c-iot/run-ptest
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.8.bb
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.9.bb
Labels: auto-backport

#1892 aws-c-mqtt: upgrade 0.8.2 -> 0.8.3, ptest, oelint-adv
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.2.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.3.bb
Labels: auto-backport

#1896 2023 01 02 master next greengrass cleanup
  recipes-iot/aws-iot-greengrass/greengrass.inc
  recipes-iot/aws-iot-greengrass/greengrass_1.11.6.bb
Labels: auto-backport

#1899 2023 01 02 master next greengrass cleanup
  recipes-iot/aws-iot-greengrass/greengrass.inc
  recipes-iot/aws-iot-greengrass/greengrass_1.11.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1898 2023 01 02 master next greengrass cleanup
  recipes-iot/aws-iot-greengrass/greengrass.inc
  recipes-iot/aws-iot-greengrass/greengrass_1.11.6.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1900 greengrass-bin: upgrade 2.9.1 -> 2.9.2, cleanup, ptest, oelint-adv
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.cert.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.pkey.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin/run-ptest
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.2.bb
  recipes-iot/aws-iot-greengrass/greengrass/config/.gitignore
  recipes-iot/aws-iot-greengrass/greengrass/greengrass.conf
Labels: auto-backport

#1901 greengrass-bin: upgrade 2.9.1 -> 2.9.2, cleanup, ptest, oelint-adv
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.cert.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.pkey.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin/run-ptest
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.2.bb
  recipes-iot/aws-iot-greengrass/greengrass/config/.gitignore
  recipes-iot/aws-iot-greengrass/greengrass/greengrass.conf
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1903 greengrass-bin: upgrade 2.9.1 -> 2.9.2, cleanup, ptest, oelint-adv
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.cert.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.pkey.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin/run-ptest
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.2.bb
  recipes-iot/aws-iot-greengrass/greengrass/config/.gitignore
  recipes-iot/aws-iot-greengrass/greengrass/greengrass.conf
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1902 greengrass-bin: upgrade 2.9.1 -> 2.9.2, cleanup, ptest, oelint-adv
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.cert.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.pkey.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin-demo/demo.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin/run-ptest
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.2.bb
  recipes-iot/aws-iot-greengrass/greengrass/config/.gitignore
  recipes-iot/aws-iot-greengrass/greengrass/greengrass.conf
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1895 aws-c-mqtt: upgrade 0.8.2 -> 0.8.3, ptest, oelint-adv
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.2.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.3.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1894 aws-c-mqtt: upgrade 0.8.2 -> 0.8.3, ptest, oelint-adv
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.2.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.3.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1893 aws-c-mqtt: upgrade 0.8.2 -> 0.8.3, ptest, oelint-adv
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.2.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.3.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1912 2023-01-05_00-09-54_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.1.bb
Labels: version-upgrade

#1913 2023-01-05_00-09-54_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.10.bb
Labels: version-upgrade

#1915 2023-01-05_00-09-54_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1917 2023-01-05_00-09-54_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1918 2023-01-05_00-09-54_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1919 2023-01-05_00-09-54_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1911 2023-01-05_00-09-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.43.bb
Labels: version-upgrade

#1914 2023-01-05_00-09-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.43.bb
Labels: version-upgrade

#1921 2023-01-05_00-09-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1925 2023-01-05_00-09-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1923 2023-01-05_00-09-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1924 2023-01-05_00-09-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1922 2023-01-05_00-09-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1927 2023-01-05_08-23-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.43.bb
Labels: version-upgrade

#1929 2023-01-05_08-23-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1930 2023-01-05_08-23-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1931 2023-01-05_08-23-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1910 amazon-kvs-producer-sdk-cpp: fix kvs_gstreamer_sample, oelint cleanup
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.3.1.bb
Labels: auto-backport

#1932 amazon-kvs-producer-sdk-cpp: fix kvs_gstreamer_sample, oelint cleanup
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.3.1.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1934 amazon-kvs-producer-sdk-cpp: fix kvs_gstreamer_sample, oelint cleanup
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.3.1.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1933 amazon-kvs-producer-sdk-cpp: fix kvs_gstreamer_sample, oelint cleanup
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.3.1.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1938 aws-c-common: upgrade 0.8.5 -> 0.8.6, oelint
  recipes-sdk/aws-c-common/aws-c-common_0.8.6.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1937 aws-c-common: upgrade 0.8.5 -> 0.8.6, oelint
  recipes-sdk/aws-c-common/aws-c-common_0.8.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1936 aws-c-common: upgrade 0.8.5 -> 0.8.6, oelint
  recipes-sdk/aws-c-common/aws-c-common_0.8.6.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1916 2023-01-05_00-09-54_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1909 aws-iot-device-sdk-cpp-v2: add mqtt5-pubsub sample, ptest, oelint-adv
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.20.0.bb
Labels: auto-backport

#1941 aws-iot-device-sdk-cpp-v2: add mqtt5-pubsub sample, ptest, oelint-adv
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.19.2.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1939 aws-iot-device-sdk-cpp-v2: add mqtt5-pubsub sample, ptest, oelint-adv
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.19.3.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1940 aws-iot-device-sdk-cpp-v2: add mqtt5-pubsub sample, ptest, oelint-adv
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.19.1.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1928 2023-01-05_08-23-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.45.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1942 2023-01-05_08-23-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.45.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1943 2023-01-05_08-23-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.45.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1944 2023-01-05_08-23-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.45.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1926 2023-01-05_08-23-01_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: version-upgrade

#1947 2023-01-05_08-23-01_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1946 2023-01-05_08-23-01_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1945 2023-01-05_08-23-01_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1949 2023-01-06_00-09-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.44.bb
Labels: version-upgrade

#1951 2023-01-06_00-09-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.44.bb
Labels: version-upgrade

#1952 2023-01-06_00-09-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.44.bb
Labels: version-upgrade

#1950 2023-01-06_00-09-39_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.32.bb
Labels: version-upgrade

#1961 2023-01-06_00-09-39_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.32.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1953 2023-01-06_00-09-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.44.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1957 2023-01-06_00-09-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.44.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1956 2023-01-06_00-09-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.44.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1958 2023-01-06_00-09-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.44.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1959 2023-01-06_00-09-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.44.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1962 2023-01-06_00-09-39_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.32.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1963 2023-01-06_00-09-39_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.32.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1954 2023-01-06_00-09-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.44.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1955 2023-01-06_00-09-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.44.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1948 aws-c-mqtt: rate limit ptests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: auto-backport

#1966 2023-01-07_00-09-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.45.bb
Labels: version-upgrade

#1967 2023-01-07_00-09-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.45.bb
Labels: version-upgrade

#1965 2023-01-07_00-09-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.45.bb
Labels: version-upgrade

#1964 2023-01-07_00-09-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.47.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#1972 2023-01-07_00-09-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.45.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1976 2023-01-07_00-09-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.45.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1971 2023-01-07_00-09-31_master-next_aws-cli
  recipes-devtools/python/python3-botocore_1.29.45.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1973 2023-01-07_00-09-31_master-next_aws-cli
  recipes-devtools/python/python3-botocore_1.29.45.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1975 2023-01-07_00-09-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.45.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1974 2023-01-07_00-09-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.45.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1977 2023-01-07_00-09-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.47.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1979 2023-01-07_00-09-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.47.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1978 2023-01-07_00-09-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.47.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1970 aws-c-mqtt: rate limit ptests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1969 aws-c-mqtt: rate limit ptests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1968 aws-c-mqtt: rate limit ptests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1980 aws-c-mqtt: reduce ptests to figure out what causing hangs on CodeBuild
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: auto-backport

#1986 aws-c-mqtt: reduce ptests to figure out what causing hangs on CodeBuild
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1985 aws-c-mqtt: reduce ptests to figure out what causing hangs on CodeBuild
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#1987 aws-c-mqtt: reduce ptests to figure out what causing hangs on CodeBuild
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#1991 2023-01-10_00-10-31_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.2.bb
Labels: version-upgrade

#1992 2023-01-10_00-10-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.46.bb
Labels: version-upgrade

#1994 2023-01-10_00-10-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.46.bb
Labels: version-upgrade

#1990 2023-01-10_00-10-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.46.bb
Labels: version-upgrade

#1995 2023-01-10_00-10-31_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1996 2023-01-10_00-10-31_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#1997 2023-01-10_00-10-31_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#1998 2023-01-10_00-10-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1999 2023-01-10_00-10-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.46.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2000 2023-01-10_00-10-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.46.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2001 2023-01-10_00-10-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.46.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2002 2023-01-10_00-10-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.46.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2003 2023-01-10_00-10-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2005 2023-01-10_00-10-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.46.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2006 2023-01-10_00-10-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.46.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2004 2023-01-10_00-10-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#1989 2023-01-10_00-10-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2009 2023-01-10_00-10-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2007 2023-01-10_00-10-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2008 2023-01-10_00-10-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2010 aws-sdk-cpp: change mechanism to disable some libs failing on arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
Labels: auto-backport

#2015 2023 01 10 master next aws iot securetunneling localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2012 aws-sdk-cpp: change mechanism to disable some libs failing on arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2016 aws-sdk-cpp: change mechanism to disable some libs failing on arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2013 aws-sdk-cpp: change mechanism to disable some libs failing on arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.10.48.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#1984 amazon-s3-gst-plugin: version upgrade
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
Labels: auto-backport

#2019 amazon-s3-gst-plugin: version upgrade
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2018 amazon-s3-gst-plugin: version upgrade
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2017 amazon-s3-gst-plugin: version upgrade
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2020 2023-01-11_00-09-58_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.3.bb
Labels: version-upgrade

#2025 2023-01-11_00-09-58_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2026 2023-01-11_00-09-58_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2024 2023-01-11_00-09-58_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2022 2023-01-11_00-09-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.47.bb
Labels: version-upgrade

#2021 2023-01-11_00-09-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.47.bb
Labels: version-upgrade

#2023 2023-01-11_00-09-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.47.bb
Labels: version-upgrade

#2031 2023-01-11_00-09-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.47.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2033 2023-01-11_00-09-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.47.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2029 2023-01-11_00-09-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.47.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2034 2023-01-11_00-09-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.47.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2035 2023-01-11_00-09-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.47.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2030 2023-01-11_00-09-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.47.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2032 2023-01-11_00-09-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.47.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2027 2023-01-11_00-09-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.47.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2028 2023-01-11_00-09-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.47.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2036 2023 01 11 master next amazoon s3 gst pluging fix
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: auto-backport

#2038 2023 01 11 master next amazoon s3 gst pluging fix
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2039 2023 01 11 master next amazoon s3 gst pluging fix
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2043 aws-c-mqtt: enable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2042 aws-c-mqtt: enable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2041 aws-c-mqtt: enable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2044 aws-c-mqtt: disable some tests again
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: auto-backport

#2047 aws-c-mqtt: disable some tests again
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2046 aws-c-mqtt: disable some tests again
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2045 aws-c-mqtt: disable some tests again
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2048 aws-c-mqtt: disable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: auto-backport

#2049 aws-c-mqtt: disable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2050 aws-c-mqtt: disable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2051 aws-c-mqtt: disable more tests
  recipes-sdk/aws-c-mqtt/aws-c-mqtt/run-ptest
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.4.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2052 2023-01-12_00-10-10_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.11.bb
Labels: version-upgrade

#2056 2023-01-12_00-10-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.48.bb
Labels: version-upgrade

#2055 2023-01-12_00-10-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.48.bb
Labels: version-upgrade

#2053 2023-01-12_00-10-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.48.bb
Labels: version-upgrade

#2057 2023-01-12_00-10-10_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2060 2023-01-12_00-10-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.48.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created
