Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-02, with the labels that each got.

#2378 2023-02-01_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.6.bb
Labels: version-upgrade

#2374 2023-02-01_00-11-17_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.9.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
Labels: version-upgrade

#2381 2023-02-01_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2377 2023-02-01_00-11-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.61.bb
Labels: version-upgrade

#2375 2023-02-01_00-11-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.61.bb
Labels: version-upgrade

#2380 2023-02-01_00-11-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.61.bb
Labels: version-upgrade

#2383 2023-02-01_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2382 2023-02-01_00-11-17_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2379 2023-02-01_00-11-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.6.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2376 2023-02-01_00-11-17_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.35.bb
Labels: version-upgrade

#2386 2023-02-01_00-11-17_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.35.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2384 2023-02-01_00-11-17_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.35.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2385 2023-02-01_00-11-17_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.35.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2391 2023-02-02_00-10-02_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.7.bb
Labels: version-upgrade

#2392 2023-02-02_00-10-02_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.24.bb
Labels: version-upgrade

#2393 2023-02-02_00-10-02_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.20.3.bb
Labels: version-upgrade

#2396 2023-02-02_00-10-02_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2397 2023-02-02_00-10-02_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2398 2023-02-02_00-10-02_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2387 2023-02-02_00-10-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.62.bb
Labels: version-upgrade

#2395 2023-02-02_00-10-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.62.bb
Labels: version-upgrade

#2389 2023-02-02_00-10-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.4.bb
Labels: version-upgrade

#2400 2023-02-02_00-10-02_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2399 2023-02-02_00-10-02_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2401 2023-02-02_00-10-02_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.24.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2402 2023-02-02_00-10-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.4.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2404 2023-02-02_00-10-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2390 2023-02-02_00-10-02_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.7.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2403 2023-02-02_00-10-02_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2388 2023-02-02_00-10-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.62.bb
Labels: version-upgrade

#2394 2023-02-02_00-10-02_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.3.bb
Labels: version-upgrade

#2407 2023-02-02_00-10-02_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2406 2023-02-02_00-10-02_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2405 2023-02-02_00-10-02_master-next_greengrass-bin
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2411 2023-02-03_00-10-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.63.bb
Labels: version-upgrade

#2409 2023-02-03_00-10-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.63.bb
Labels: version-upgrade

#2408 2023-02-03_00-10-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.9.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2410 2023-02-03_00-10-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.63.bb
Labels: version-upgrade

#2412 2023-02-04_00-09-40_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.64.bb
Labels: version-upgrade

#2414 2023-02-04_00-09-40_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.64.bb
Labels: version-upgrade

#2416 2023-02-04_00-09-40_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: version-upgrade

#2415 2023-02-04_00-09-40_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.10.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2413 2023-02-04_00-09-40_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.64.bb
Labels: version-upgrade

#2417 2023-02-04_00-09-40_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.10.bb
Labels: version-upgrade

#2422 2023-02-05_00-10-27_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.15.bb
Labels: version-upgrade

#2421 2023-02-05_00-10-27_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.4.bb
Labels: version-upgrade

#2429 2023-02-07_00-09-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.65.bb
Labels: version-upgrade

#2428 2023-02-07_00-09-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.65.bb
Labels: version-upgrade

#2427 2023-02-07_00-09-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.11.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2426 2023-02-07_00-09-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.65.bb
Labels: version-upgrade

#2435 2023-02-08_00-10-38_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.4.bb
Labels: version-upgrade

#2437 2023-02-08_00-10-38_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.66.bb
Labels: version-upgrade

#2433 2023-02-08_00-10-38_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.66.bb
Labels: version-upgrade

#2434 2023-02-08_00-10-38_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.3.0.bb
  recipes-sdk/aws-lc/aws-lc_1.4.0.bb
Labels: version-upgrade

#2432 2023-02-08_00-10-38_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: version-upgrade

#2430 2023-02-08_00-10-38_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.7.bb
Labels: version-upgrade

#2442 2023-02-08_00-10-38_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2443 2023-02-08_00-10-38_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2441 2023-02-08_00-10-38_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2431 2023-02-08_00-10-38_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.12.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2440 2023-02-08_00-10-38_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.4.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2444 2023-02-08_00-10-38_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2438 2023-02-08_00-10-38_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2439 2023-02-08_00-10-38_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2445 2023-02-08_00-10-38_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2448 aws-c-common: disable non working ptests
  recipes-sdk/aws-c-common/files/run-ptest
Labels: auto-backport

#2449 aws-c-common: disable non working ptests
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2450 aws-c-common: disable non working ptests
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2451 aws-c-common: disable non working ptests
  recipes-sdk/aws-c-common/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2453 2023-02-09_00-02-12_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.10.bb
  recipes-sdk/aws-crt-python/files/0001-fix-library-suffix.patch
Labels: version-upgrade

#2454 2023-02-09_00-02-12_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.67.bb
Labels: version-upgrade

#2455 2023-02-09_00-02-12_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.5.bb
Labels: version-upgrade

#2458 2023-02-09_00-02-12_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2460 2023-02-09_00-02-12_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.67.bb
Labels: version-upgrade

#2459 2023-02-09_00-02-12_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.12.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2461 2023-02-09_00-02-12_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.13.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2466 2023-02-09_00-02-12_master-next_s2n
  recipes-sdk/s2n/s2n/run-ptest
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2468 2023-02-09_00-02-12_master-next_s2n
  recipes-sdk/s2n/s2n/run-ptest
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2467 2023-02-09_00-02-12_master-next_s2n
  recipes-sdk/s2n/s2n/run-ptest
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2470 2023-02-10_00-02-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.68.bb
Labels: version-upgrade

#2471 2023-02-10_00-02-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.68.bb
Labels: version-upgrade

#2472 2023-02-10_00-02-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.68.bb
Labels: version-upgrade

#2478 2023-02-10_00-02-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.68.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2474 2023-02-10_00-02-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.68.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2480 2023-02-10_00-02-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.68.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2469 2023-02-10_00-02-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.14.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2473 2023-02-10_00-02-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.68.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2477 2023-02-10_00-02-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.68.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2481 2023-02-10_00-02-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.68.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2476 2023-02-10_00-02-20_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.68.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2475 2023-02-10_00-02-20_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.68.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2479 2023-02-10_00-02-20_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.68.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2482 2023-02-10_00-02-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.14.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2484 2023-02-10_00-02-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.14.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2483 2023-02-10_00-02-20_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.14.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2485 2023-02-13_00-02-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.69.bb
Labels: version-upgrade

#2487 2023-02-13_00-02-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.69.bb
Labels: version-upgrade

#2488 2023-02-13_00-02-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.69.bb
Labels: version-upgrade

#2489 2023-02-13_00-02-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.69.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2490 2023-02-13_00-02-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.69.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2491 2023-02-13_00-02-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.69.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2496 2023-02-13_00-02-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.69.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2497 2023-02-13_00-02-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.69.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2492 2023-02-13_00-02-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.69.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2494 2023-02-13_00-02-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.69.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2495 2023-02-13_00-02-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.69.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2493 2023-02-13_00-02-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.69.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2486 2023-02-13_00-02-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.15.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2498 2023-02-13_00-02-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.15.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2500 2023-02-13_00-02-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.15.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2499 2023-02-13_00-02-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.15.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2504 2023-02-14_00-15-05_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.11.bb
Labels: version-upgrade

#2503 2023-02-14_00-15-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.70.bb
Labels: version-upgrade

#2505 2023-02-14_00-15-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.70.bb
Labels: version-upgrade

#2506 2023-02-14_00-15-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.70.bb
Labels: version-upgrade

#2510 2023-02-14_00-15-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.70.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2512 2023-02-14_00-15-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.70.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2514 2023-02-14_00-15-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.70.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2508 2023-02-14_00-15-05_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2509 2023-02-14_00-15-05_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2517 2023-02-14_00-15-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.70.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2518 2023-02-14_00-15-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.70.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2513 2023-02-14_00-15-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.70.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2502 2023-02-14_00-15-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.16.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2516 2023-02-14_00-15-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.70.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2507 2023-02-14_00-15-05_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2515 2023-02-14_00-15-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.70.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2511 2023-02-14_00-15-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.70.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2521 2023-02-14_00-15-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.16.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2520 2023-02-14_00-15-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.16.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2524 2023-02-15_00-15-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.71.bb
Labels: version-upgrade

#2523 2023-02-15_00-15-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.71.bb
Labels: version-upgrade

#2525 2023-02-15_00-15-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.71.bb
Labels: version-upgrade

#2526 2023-02-15_00-15-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.71.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2527 2023-02-15_00-15-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.71.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2528 2023-02-15_00-15-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.71.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2529 2023-02-15_00-15-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.71.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2532 2023-02-15_00-15-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.71.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2533 2023-02-15_00-15-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.71.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2534 2023-02-15_00-15-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.71.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2530 2023-02-15_00-15-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.71.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2531 2023-02-15_00-15-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.71.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2522 2023-02-15_00-15-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.17.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2535 2023-02-15_00-15-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.17.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2536 2023-02-15_00-15-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.17.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2537 2023-02-15_00-15-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.17.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2539 2023-02-16_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.72.bb
Labels: version-upgrade

#2540 2023-02-16_00-14-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.72.bb
Labels: version-upgrade

#2542 2023-02-16_00-14-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.72.bb
Labels: version-upgrade

#2544 2023-02-16_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.72.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created
