Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-10, with the labels that each got.

#5588 2023-09-29_00-14-05_master-next_aws-iot-fleetwise-edge
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.0.8.bb
Labels: version-upgrade

#5610 2023-10-03_00-13-24_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: version-upgrade

#5609 2023-10-03_00-13-24_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.58.bb
Labels: version-upgrade

#5608 2023-10-03_00-13-24_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.174.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5607 2023-10-03_00-13-24_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.29.1.bb
Labels: version-upgrade

#5605 2023-10-03_00-13-24_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.58.bb
Labels: version-upgrade

#5606 2023-10-03_00-13-24_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.58.bb
Labels: version-upgrade

#5622 2023-10-03_00-13-24_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.29.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5620 2023-10-03_00-13-24_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.29.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5612 2023-10-03_00-13-24_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5613 2023-10-03_00-13-24_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5614 2023-10-03_00-13-24_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5616 2023-10-03_00-13-24_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5623 2023-10-03_00-13-24_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5615 2023-10-03_00-13-24_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5625 2023-10-03_00-13-24_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5626 2023-10-03_00-13-24_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5628 2023-10-03_00-13-24_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5611 2023-10-03_00-13-24_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5624 2023-10-03_00-13-24_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5621 2023-10-03_00-13-24_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.29.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5627 2023-10-03_00-13-24_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5617 2023-10-03_00-13-24_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.174.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5618 2023-10-03_00-13-24_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.174.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5619 2023-10-03_00-13-24_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.174.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5635 layer.conf: mask python3-boto* in meta-python
  conf/layer.conf
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5636 layer.conf: mask python3-boto* in meta-python
  conf/layer.conf
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5637 layer.conf: mask python3-boto* in meta-python
  conf/layer.conf
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#5633 2023-10-04_00-13-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.59.bb
Labels: version-upgrade

#5629 2023-10-04_00-13-56_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.24.0.bb
Labels: version-upgrade

#5632 2023-10-04_00-13-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.59.bb
Labels: version-upgrade

#5631 2023-10-04_00-13-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.175.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5630 2023-10-04_00-13-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.59.bb
Labels: version-upgrade

#5638 2023-10-04_00-13-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.59.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5642 s2n: fix fixme comment
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#5654 2023-10-04_00-13-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.59.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5648 2023-10-04_00-13-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.59.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5647 2023-10-04_00-13-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.59.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5653 2023-10-04_00-13-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.59.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5640 2023-10-04_00-13-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.59.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5643 s2n: fix fixme comment
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5650 2023-10-04_00-13-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.175.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5652 2023-10-04_00-13-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.175.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5649 2023-10-04_00-13-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.59.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5641 s2n: fix fixme comment
  recipes-sdk/s2n/s2n_1.3.52.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5639 2023-10-04_00-13-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.59.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5655 2023-10-04_00-13-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.59.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5660 2023-10-05_00-14-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.60.bb
Labels: version-upgrade

#5659 2023-10-05_00-14-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.60.bb
Labels: version-upgrade

#5657 2023-10-05_00-14-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.60.bb
Labels: version-upgrade

#5667 2023-10-05_00-14-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.60.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5670 2023-10-05_00-14-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.60.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5664 2023-10-05_00-14-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.60.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5663 2023-10-05_00-14-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5669 2023-10-05_00-14-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5665 2023-10-05_00-14-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5662 2023-10-05_00-14-56_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5668 2023-10-05_00-14-56_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5666 2023-10-05_00-14-56_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5656 2023-10-05_00-14-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.176.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5658 2023-10-05_00-14-56_master-next_amazon-s3-gst-plugin
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: version-upgrade

#5677 2023-10-05_00-14-56_master-next_amazon-s3-gst-plugin
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5673 2023-10-05_00-14-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.176.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5674 2023-10-05_00-14-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.176.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5676 2023-10-05_00-14-56_master-next_amazon-s3-gst-plugin
  recipes-multimedia/amazon-s3-gst-plugin/amazon-s3-gst-plugin_git.bb
  recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5672 2023-10-05_00-14-56_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.176.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5682 2023-10-06_00-12-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.24.2.bb
Labels: version-upgrade

#5683 2023-10-06_00-12-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.61.bb
Labels: version-upgrade

#5681 2023-10-06_00-12-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.61.bb
Labels: version-upgrade

#5680 2023-10-06_00-12-49_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.54.bb
Labels: version-upgrade

#5684 2023-10-06_00-12-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.24.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5698 2023-10-06_00-12-49_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.54.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5690 2023-10-06_00-12-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5695 2023-10-06_00-12-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5701 2023-10-06_00-12-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5689 2023-10-06_00-12-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.177.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5702 firecracker-bin, jailer-bin: disable debug split
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: auto-backport

#5685 2023-10-06_00-12-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.24.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5703 firecracker-bin, jailer-bin: disable debug split
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#5704 firecracker-bin, jailer-bin: disable debug split
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5696 2023-10-06_00-12-49_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.54.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5694 2023-10-06_00-12-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.61.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5697 2023-10-06_00-12-49_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.54.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5686 2023-10-06_00-12-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.24.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5699 2023-10-06_00-12-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.61.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5692 2023-10-06_00-12-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.61.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5687 2023-10-06_00-12-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.177.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5700 2023-10-06_00-12-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5693 2023-10-06_00-12-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5706 aws-iot-securetunneling-localproxy: fix DSO missing from command line
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: auto-backport

#5691 2023-10-06_00-12-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5705 firecracker-bin, jailer-bin: disable debug split
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5707 aws-iot-securetunneling-localproxy: fix DSO missing from command line
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5708 aws-iot-securetunneling-localproxy: fix DSO missing from command line
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5688 2023-10-06_00-12-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.177.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5709 firecracker-bin, jailer-bin: add INHIBIT_PACKAGE_STRIP
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: auto-backport

#5711 firecracker-bin, jailer-bin: add INHIBIT_PACKAGE_STRIP
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5710 firecracker-bin, jailer-bin: add INHIBIT_PACKAGE_STRIP
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5713 add Upstream-Status for every patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: auto-backport

#5714 add Upstream-Status for every patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5715 add Upstream-Status for every patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5716 amazon-kvs-webrtc-sdk: add ptest, sample package
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.8.1.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/ptest_result.py
  recipes-sdk/amazon-kvs-webrtc-sdk/files/run-ptest
Labels: auto-backport

#5717 amazon-kvs-webrtc-sdk: add ptest, sample package
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.8.1.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/ptest_result.py
  recipes-sdk/amazon-kvs-webrtc-sdk/files/run-ptest
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5718 amazon-kvs-webrtc-sdk: add ptest, sample package
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.8.1.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/ptest_result.py
  recipes-sdk/amazon-kvs-webrtc-sdk/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5719 2023-10-10_00-13-30_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.30.0.bb
Labels: version-upgrade

#5720 2023-10-10_00-13-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.62.bb
Labels: version-upgrade

#5721 2023-10-10_00-13-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.62.bb
Labels: version-upgrade

#5723 2023-10-10_00-13-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.62.bb
Labels: version-upgrade

#5722 2023-10-10_00-13-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.178.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5724 2023-10-10_00-13-30_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.30.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5727 2023-10-10_00-13-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.62.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5734 2023-10-10_00-13-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.62.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5732 2023-10-10_00-13-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.62.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5725 2023-10-10_00-13-30_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.30.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5726 2023-10-10_00-13-30_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.30.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5729 2023-10-10_00-13-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.62.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5728 2023-10-10_00-13-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.62.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5731 2023-10-10_00-13-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.62.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5733 2023-10-10_00-13-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.62.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5730 2023-10-10_00-13-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.62.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5735 2023-10-10_00-13-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.62.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5736 2023-10-10_00-13-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.178.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5738 2023-10-10_00-13-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.178.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5737 2023-10-10_00-13-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.178.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5739 2023-10-13_00-12-53_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.5.bb
Labels: version-upgrade

#5742 2023-10-13_00-12-53_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.33.bb
Labels: version-upgrade

#5745 2023-10-13_00-12-53_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5747 2023-10-13_00-12-53_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5741 2023-10-13_00-12-53_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.63.bb
Labels: version-upgrade

#5748 2023-10-13_00-12-53_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.33.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5743 2023-10-13_00-12-53_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.63.bb
Labels: version-upgrade

#5750 2023-10-13_00-12-53_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.33.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5751 2023-10-13_00-12-53_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.63.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5752 2023-10-13_00-12-53_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.63.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5740 2023-10-13_00-12-53_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.179.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5744 2023-10-13_00-12-53_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.63.bb
Labels: version-upgrade

#5754 2023-10-13_00-12-53_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.63.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5756 2023-10-13_00-12-53_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.63.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5761 2023-10-13_00-12-53_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.63.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5762 2023-10-13_00-12-53_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.63.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5746 2023-10-13_00-12-53_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5749 2023-10-13_00-12-53_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.33.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5753 2023-10-13_00-12-53_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.63.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5755 2023-10-13_00-12-53_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.63.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5760 2023-10-13_00-12-53_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.63.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5759 2023-10-13_00-12-53_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.179.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5758 2023-10-13_00-12-53_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.179.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5757 2023-10-13_00-12-53_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.179.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5763 2023-10-17_00-14-30_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.9.7.bb
Labels: version-upgrade

#5764 2023-10-17_00-14-30_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.18.bb
Labels: version-upgrade
