Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-09, with the labels that each got.

#5270 2023-09-01_00-15-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.39.bb
Labels: version-upgrade

#5271 2023-09-01_00-15-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.39.bb
Labels: version-upgrade

#5272 2023-09-01_00-15-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.39.bb
Labels: version-upgrade

#5277 2023-09-01_00-15-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.39.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5278 2023-09-01_00-15-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.39.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5280 2023-09-01_00-15-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.39.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5269 2023-09-01_00-15-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.155.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5281 2023-09-01_00-15-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.39.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5279 2023-09-01_00-15-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.39.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5282 2023-09-01_00-15-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.39.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5283 2023-09-01_00-15-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.155.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5285 2023-09-01_00-15-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.155.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5284 2023-09-01_00-15-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.155.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5287 2023-09-01_00-15-10_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5273 2023-09-01_00-15-10_master-next_corretto-17-bin
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.8.8.1.bb
Labels: version-upgrade

#5276 2023-09-01_00-15-10_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.15.0.bb
Labels: version-upgrade

#5290 2023-09-01_00-15-10_master-next_corretto-17-bin
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.8.8.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5267 2023-09-01_00-15-10_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-c_1.5.0.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.0.bb
Labels: version-upgrade

#5275 2023-09-01_00-15-10_master-next_corretto-11-bin
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.20.9.1.bb
Labels: version-upgrade

#5292 2023-09-01_00-15-10_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.15.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5299 2023-09-01_00-15-10_master-next_corretto-11-bin
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.20.9.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5291 2023-09-01_00-15-10_master-next_corretto-17-bin
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.8.8.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5295 2023-09-01_00-15-10_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-pic_git.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-c_1.5.0.bb
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/fix_kvs_gstreamer_sample.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5300 2023-09-01_00-15-10_master-next_corretto-11-bin
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.20.9.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5274 2023-09-01_00-15-10_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/disable_build_deps.patch
Labels: version-upgrade

#5303 aws-iot-device-client: readd recipe, because of fixes
  recipes-iot/aws-iot-device-client/aws-iot-device-client_git.bb
  recipes-iot/aws-iot-device-client/files/fix_jobs_warning_error.patch
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#5304 aws-iot-device-client: readd recipe, because of fixes
  recipes-iot/aws-iot-device-client/aws-iot-device-client_git.bb
  recipes-iot/aws-iot-device-client/files/fix_jobs_warning_error.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5305 2023-09-01_00-15-10_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/disable_build_deps.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5311 2023-09-05_00-13-16_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/disable_build_deps.patch
Labels: version-upgrade

#5314 2023-09-05_00-13-16_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb
Labels: version-upgrade

#5316 2023-09-05_00-13-16_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_git.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/disable_build_deps.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5318 2023-09-05_00-13-16_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5317 2023-09-05_00-13-16_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5319 2023-09-05_00-13-16_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5309 2023-09-05_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.40.bb
Labels: version-upgrade

#5312 2023-09-05_00-13-16_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.3.bb
Labels: version-upgrade

#5320 2023-09-05_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.40.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5321 2023-09-05_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.40.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5322 2023-09-05_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.40.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5313 2023-09-05_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.40.bb
Labels: version-upgrade

#5323 2023-09-05_00-13-16_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5324 2023-09-05_00-13-16_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5315 2023-09-05_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.40.bb
Labels: version-upgrade

#5326 2023-09-05_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.40.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5327 2023-09-05_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.40.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5310 2023-09-05_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.156.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5325 2023-09-05_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.40.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5328 2023-09-05_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.40.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5329 2023-09-05_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.40.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5330 2023-09-05_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.40.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5331 2023-09-05_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.156.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5332 2023-09-05_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.156.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5333 2023-09-05_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.156.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5334 2023-09-06_00-13-41_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
Labels: version-upgrade

#5339 2023-09-06_00-13-41_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5340 2023-09-06_00-13-41_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5341 2023-09-06_00-13-41_master-next_amazon-kvs-producer-sdk-cpp
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp_3.4.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5336 2023-09-06_00-13-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.41.bb
Labels: version-upgrade

#5337 2023-09-06_00-13-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.41.bb
Labels: version-upgrade

#5342 2023-09-06_00-13-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.41.bb
Labels: version-upgrade

#5346 2023-09-06_00-13-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.41.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5343 2023-09-06_00-13-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.41.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5350 2023-09-06_00-13-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.41.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5338 2023-09-06_00-13-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.157.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5344 2023-09-06_00-13-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.41.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5347 2023-09-06_00-13-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.41.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5345 2023-09-06_00-13-41_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.41.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5349 2023-09-06_00-13-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.41.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5348 2023-09-06_00-13-41_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.41.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5351 2023-09-06_00-13-41_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.41.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5352 2023-09-06_00-13-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.157.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5354 2023-09-06_00-13-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.157.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5353 2023-09-06_00-13-41_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.157.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5356 2023-09-07_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.42.bb
Labels: version-upgrade

#5357 2023-09-07_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.42.bb
Labels: version-upgrade

#5359 2023-09-07_00-13-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.23.1.bb
Labels: version-upgrade

#5358 2023-09-07_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.42.bb
Labels: version-upgrade

#5361 2023-09-07_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.42.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5362 2023-09-07_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.42.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5363 2023-09-07_00-13-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.42.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5365 2023-09-07_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.42.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5366 2023-09-07_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.42.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5364 2023-09-07_00-13-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.42.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5367 2023-09-07_00-13-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.23.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5368 2023-09-07_00-13-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.23.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5372 2023-09-07_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.42.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5355 2023-09-07_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.158.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5369 2023-09-07_00-13-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.23.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5371 2023-09-07_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.42.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5370 2023-09-07_00-13-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.42.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5373 2023-09-07_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.158.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5375 2023-09-07_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.158.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5374 2023-09-07_00-13-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.158.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5376 2023-09-08_00-12-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.43.bb
Labels: version-upgrade

#5383 2023-09-08_00-12-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5381 2023-09-08_00-12-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5382 2023-09-08_00-12-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5378 2023-09-08_00-12-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.43.bb
Labels: version-upgrade

#5379 2023-09-08_00-12-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.43.bb
Labels: version-upgrade

#5386 2023-09-08_00-12-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5377 2023-09-08_00-12-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.159.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5384 2023-09-08_00-12-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5385 2023-09-08_00-12-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5387 2023-09-08_00-12-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.43.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5389 2023-09-08_00-12-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5388 2023-09-08_00-12-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5390 2023-09-08_00-12-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.159.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5392 2023-09-08_00-12-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.159.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5391 2023-09-08_00-12-27_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.159.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5396 2023 09 11 master next amazon kvs webrtc sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.8.1.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/files/disable_build_deps.patch
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5399 aws-iot-device-client: still broken, disable
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: auto-backport

#5400 aws-iot-device-client: still broken, disable
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: backport, auto-integrate, auto-created, auto-backport, mickledore

#5401 aws-iot-device-client: still broken, disable
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#5402 aws-iot-device-client: still broken, disable
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.8.bb_broken
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#5403 2023-09-12_00-13-39_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.17.bb
Labels: version-upgrade

#5404 2023-09-12_00-13-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.45.bb
Labels: version-upgrade

#5411 2023-09-12_00-13-39_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5405 2023-09-12_00-13-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.45.bb
Labels: version-upgrade

#5410 2023-09-12_00-13-39_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5414 2023-09-12_00-13-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.45.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5408 2023-09-12_00-13-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.45.bb
Labels: version-upgrade

#5413 2023-09-12_00-13-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.45.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5415 2023-09-12_00-13-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.45.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5417 2023-09-12_00-13-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.45.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5406 2023-09-12_00-13-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.161.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5418 2023-09-12_00-13-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.45.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5419 2023-09-12_00-13-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.45.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5409 2023-09-12_00-13-39_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5412 2023-09-12_00-13-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.45.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5416 2023-09-12_00-13-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.45.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5420 2023-09-12_00-13-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.45.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5423 2023-09-12_00-13-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.161.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5421 2023-09-12_00-13-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.161.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5422 2023-09-12_00-13-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.161.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5424 2023-09-13_00-13-33_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.46.bb
Labels: version-upgrade

#5425 2023-09-13_00-13-33_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.46.bb
Labels: version-upgrade

#5426 2023-09-13_00-13-33_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.46.bb
Labels: version-upgrade

#5429 2023-09-13_00-13-33_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.46.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5430 2023-09-13_00-13-33_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5432 2023-09-13_00-13-33_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5433 2023-09-13_00-13-33_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.46.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5435 2023-09-13_00-13-33_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.46.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5437 2023-09-13_00-13-33_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.46.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5428 2023-09-13_00-13-33_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.162.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#5440 2023-09-13_00-13-33_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.162.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#5438 2023-09-13_00-13-33_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.162.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5439 2023-09-13_00-13-33_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.162.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#5441 FWE: Add configuration parameters
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.0.7.bb
Labels: backport

#5448 2023-09-13_00-13-33_master-next_s2n
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.3.51.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#5449 2023-09-13_00-13-33_master-next_s2n
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.3.51.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore
