Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-07, with the labels that each got.

#4413 2023-07-04_00-16-26_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.12.bb
Labels: version-upgrade

#4417 2023-07-04_00-16-26_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.12.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4416 2023-07-04_00-16-26_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4420 2023-07-04_00-16-26_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1297.0.bb
Labels: version-upgrade

#4415 2023-07-04_00-16-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.0.bb
Labels: version-upgrade

#4418 2023-07-04_00-16-26_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4419 2023-07-04_00-16-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.0.bb
Labels: version-upgrade

#4428 2023-07-04_00-16-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4426 2023-07-04_00-16-26_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1297.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4427 2023-07-04_00-16-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4429 2023-07-04_00-16-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4422 2023-07-04_00-16-26_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.0.bb
Labels: version-upgrade

#4425 2023-07-04_00-16-26_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1297.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4423 2023-07-04_00-16-26_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.3.1.bb
Labels: version-upgrade

#4421 2023-07-04_00-16-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.0.bb
Labels: version-upgrade

#4412 2023-07-04_00-16-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.113.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4424 2023-07-04_00-16-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.0.bb
Labels: version-upgrade

#4431 2023-07-04_00-16-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4434 2023-07-04_00-16-26_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4437 2023-07-04_00-16-26_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.3.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4438 2023-07-04_00-16-26_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.3.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4433 2023-07-04_00-16-26_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4435 2023-07-04_00-16-26_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4436 2023-07-04_00-16-26_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.3.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4446 2023-07-04_00-16-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4440 2023-07-04_00-16-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4432 2023-07-04_00-16-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4430 2023-07-04_00-16-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4441 2023-07-04_00-16-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4447 2023-07-04_00-16-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4439 2023-07-04_00-16-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4445 2023-07-04_00-16-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4443 2023-07-04_00-16-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.113.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4442 2023-07-04_00-16-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.113.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4414 2023-07-04_00-16-26_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.27.bb
Labels: version-upgrade

#4448 2023-07-04_00-16-26_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.27.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4449 2023-07-04_00-16-26_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4450 2023-07-04_00-16-26_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4444 2023-07-04_00-16-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.113.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4451 2023-07-06_00-16-46_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.1.bb
Labels: version-upgrade

#4452 2023-07-06_00-16-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.1.bb
Labels: version-upgrade

#4453 2023-07-06_00-16-46_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.3.bb
Labels: version-upgrade

#4455 2023-07-06_00-16-46_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4458 2023-07-06_00-16-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4461 2023-07-06_00-16-46_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.1.bb
Labels: version-upgrade

#4464 2023-07-06_00-16-46_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4465 2023-07-06_00-16-46_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.14.bb
Labels: version-upgrade

#4456 2023-07-06_00-16-46_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4468 2023-07-06_00-16-46_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4463 2023-07-06_00-16-46_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.20.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4459 2023-07-06_00-16-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4469 2023-07-06_00-16-46_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.14.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4470 2023-07-06_00-16-46_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4454 2023-07-06_00-16-46_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.28.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4460 2023-07-06_00-16-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.27.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4466 2023-07-06_00-16-46_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4457 2023-07-06_00-16-46_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.114.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4467 2023-07-06_00-16-46_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.30.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4471 2023-07-06_00-16-46_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.8.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4474 2023-07-06_00-16-46_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.114.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4472 2023-07-06_00-16-46_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.114.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4473 2023-07-06_00-16-46_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.114.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4476 2023-07-07_00-15-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.0.bb
Labels: version-upgrade

#4477 2023-07-07_00-15-29_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.23.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#4478 2023-07-07_00-15-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.0.bb
Labels: version-upgrade

#4480 2023-07-07_00-15-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4479 2023-07-07_00-15-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4481 2023-07-07_00-15-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4482 2023-07-07_00-15-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.0.bb
Labels: version-upgrade

#4486 2023-07-07_00-15-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4487 2023-07-07_00-15-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4488 2023-07-07_00-15-29_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4489 2023-07-07_00-15-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.28.bb
Labels: version-upgrade

#4490 2023-07-07_00-15-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4491 2023-07-07_00-15-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4492 2023-07-07_00-15-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4493 2023-07-07_00-15-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.28.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4495 2023-07-07_00-15-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.28.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4494 2023-07-07_00-15-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.28.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4484 2023-07-07_00-15-29_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.23.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4496 2023-07-07_00-15-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.115.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4498 2023-07-07_00-15-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.115.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4497 2023-07-07_00-15-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.115.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4502 2023-07-11_00-16-07_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.24.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#4503 2023-07-11_00-16-07_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.12.0.bb
Labels: version-upgrade

#4505 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.25.0.bb
Labels: version-upgrade

#4511 2023-07-11_00-16-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.1.bb
Labels: version-upgrade

#4513 2023-07-11_00-16-07_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.24.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4514 2023-07-11_00-16-07_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.12.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4516 2023-07-11_00-16-07_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.12.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4518 2023-07-11_00-16-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4519 2023-07-11_00-16-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4520 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.25.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4522 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.25.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4523 2023-07-11_00-16-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4508 2023-07-11_00-16-07_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.13.bb
Labels: version-upgrade

#4509 2023-07-11_00-16-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.1.bb
Labels: version-upgrade

#4526 2023-07-11_00-16-07_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4527 2023-07-11_00-16-07_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.13.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4529 2023-07-11_00-16-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4531 2023-07-11_00-16-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4533 2023-07-11_00-16-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4534 2023-07-11_00-16-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4510 2023-07-11_00-16-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.116.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4512 2023-07-11_00-16-07_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.16.24.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4515 2023-07-11_00-16-07_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.12.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4517 2023-07-11_00-16-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4521 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.25.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4528 2023-07-11_00-16-07_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.3.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4524 2023-07-11_00-16-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4530 2023-07-11_00-16-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4532 2023-07-11_00-16-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4536 2023-07-11_00-16-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.116.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4537 2023-07-11_00-16-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.116.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4535 2023-07-11_00-16-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.116.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4506 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.16.0.bb
Labels: version-upgrade

#4538 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.16.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4540 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.16.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4539 2023-07-11_00-16-07_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.16.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4542 2023-07-12_00-16-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.2.bb
Labels: version-upgrade

#4541 2023-07-12_00-16-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.2.bb
Labels: version-upgrade

#4543 2023-07-12_00-16-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.2.bb
Labels: version-upgrade

#4549 2023-07-12_00-16-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4550 2023-07-12_00-16-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4548 2023-07-12_00-16-55_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4546 2023-07-12_00-16-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4547 2023-07-12_00-16-55_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4553 2023-07-12_00-16-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4544 2023-07-12_00-16-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.117.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#4556 2023-07-12_00-16-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.117.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4555 2023-07-12_00-16-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.117.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4554 2023-07-12_00-16-55_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.117.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4551 2023-07-12_00-16-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4552 2023-07-12_00-16-55_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4557 Update greengrass-bin_2.9.6.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: auto-backport

#4560 Update greengrass-bin_2.9.6.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#4558 Update greengrass-bin_2.9.6.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#4564 2023-07-14_00-17-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.3.bb
Labels: version-upgrade

#4565 2023-07-14_00-17-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.3.bb
Labels: version-upgrade

#4566 2023-07-14_00-17-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.3.bb
Labels: version-upgrade

#4569 2023-07-14_00-17-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4567 2023-07-14_00-17-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4568 2023-07-14_00-17-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.29.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4570 2023-07-14_00-17-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4571 2023-07-14_00-17-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4573 2023-07-14_00-17-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#4572 2023-07-14_00-17-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.28.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4574 2023-07-14_00-17-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#4575 2023-07-14_00-17-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.31.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, mickledore

#4563 2023-07-14_00-17-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.118.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade
