Repository aws4embeddedlinux/meta-aws, pull requests merged in 2023-03, with the labels that each got.

#2694 2023-03-01_00-16-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.81.bb
Labels: version-upgrade

#2695 2023-03-01_00-16-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.81.bb
Labels: version-upgrade

#2693 2023-03-01_00-16-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.81.bb
Labels: version-upgrade

#2696 2023-03-01_00-16-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2697 2023-03-01_00-16-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2699 2023-03-01_00-16-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.81.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2701 2023-03-01_00-16-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2702 2023-03-01_00-16-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2704 2023-03-01_00-16-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2700 2023-03-01_00-16-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2703 2023-03-01_00-16-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.81.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2692 2023-03-01_00-16-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2705 2023-03-01_00-16-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2706 2023-03-01_00-16-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2707 2023-03-01_00-16-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.27.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2708 2023-03-02_00-15-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.82.bb
Labels: version-upgrade

#2710 2023-03-02_00-15-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.82.bb
Labels: version-upgrade

#2709 2023-03-02_00-15-34_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.5.0.bb
Labels: version-upgrade

#2715 2023-03-02_00-15-34_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.20.bb
Labels: version-upgrade

#2712 2023-03-02_00-15-34_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.8.bb
Labels: version-upgrade

#2718 2023-03-02_00-15-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2720 2023-03-02_00-15-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2717 2023-03-02_00-15-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2719 2023-03-02_00-15-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2726 2023-03-02_00-15-34_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2721 2023-03-02_00-15-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2727 2023-03-02_00-15-34_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2728 2023-03-02_00-15-34_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.8.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2729 2023-03-02_00-15-34_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.19.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2713 2023-03-02_00-15-34_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.5.21.bb
Labels: version-upgrade

#2723 2023-03-02_00-15-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.18.bb
Labels: version-upgrade

#2724 2023-03-02_00-15-34_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2725 2023-03-02_00-15-34_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.2.20.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2714 2023-03-02_00-15-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.82.bb
Labels: version-upgrade

#2730 2023-03-02_00-15-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.5.bb
Labels: version-upgrade

#2722 2023-03-02_00-15-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2732 2023-03-02_00-15-34_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.5.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2731 2023-03-02_00-15-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.12.bb
Labels: version-upgrade

#2733 2023-03-02_00-15-34_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.5.21.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2738 2023-03-02_00-15-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2734 2023-03-02_00-15-34_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.5.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2740 2023-03-02_00-15-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2739 2023-03-02_00-15-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2735 2023-03-02_00-15-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.18.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2736 2023-03-02_00-15-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2737 2023-03-02_00-15-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.13.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2743 2023-03-02_00-15-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2744 2023-03-02_00-15-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.5.bb
Labels: version-upgrade

#2742 2023-03-02_00-15-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2741 2023-03-02_00-15-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.7.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2745 2023-03-02_00-15-34_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.25.bb
Labels: version-upgrade

#2747 2023-03-02_00-15-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.12.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2746 2023-03-02_00-15-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2748 2023-03-02_00-15-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2750 2023-03-02_00-15-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2751 2023-03-02_00-15-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2749 2023-03-02_00-15-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2711 2023-03-02_00-15-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.28.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2752 2023-03-02_00-15-34_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2753 2023-03-02_00-15-34_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.25.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2754 2023-03-02_00-15-34_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.6.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2755 2023-03-02_00-15-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.28.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2757 2023-03-02_00-15-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.28.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2756 2023-03-02_00-15-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.28.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2760 2023-03-03_01-54-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.83.bb
Labels: version-upgrade

#2759 2023-03-03_01-54-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.83.bb
Labels: version-upgrade

#2766 2023-03-03_01-54-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.83.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2770 2023-03-03_01-54-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.83.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2767 2023-03-03_01-54-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.83.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2764 2023-03-03_01-54-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.83.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2765 2023-03-03_01-54-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2769 2023-03-03_01-54-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2772 2023-03-03_01-54-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.83.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2768 2023-03-03_01-54-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.83.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2762 2023-03-03_01-54-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2771 2023-03-03_01-54-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2775 2023-03-03_01-54-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2773 2023-03-03_01-54-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2774 2023-03-03_01-54-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2763 2023-03-03_01-54-06_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.38.bb
Labels: version-upgrade

#2778 2023-03-03_01-54-06_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.38.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2777 2023-03-03_01-54-06_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.38.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2776 2023-03-03_01-54-06_master-next_s2n
  recipes-sdk/s2n/s2n_1.3.38.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2761 2023-03-03_01-54-06_master-next_neo-ai-tvm
  recipes-devtools/amazon-sagemaker-neo-tvm/neo-ai-tvm_0.11.0.bb
Labels: version-upgrade

#2785 2023-03-03_01-54-06_master-next_neo-ai-tvm
  recipes-devtools/amazon-sagemaker-neo-tvm/neo-ai-tvm_0.11.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2786 2023-03-03_01-54-06_master-next_neo-ai-tvm
  recipes-devtools/amazon-sagemaker-neo-tvm/neo-ai-tvm_0.11.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2787 s2n: fix ptest for qemuarm
  recipes-sdk/s2n/s2n/run-ptest
Labels: auto-backport

#2788 s2n: fix ptest for qemuarm
  recipes-sdk/s2n/s2n/run-ptest
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2789 s2n: fix ptest for qemuarm
  recipes-sdk/s2n/s2n/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2790 s2n: fix ptest for qemuarm
  recipes-sdk/s2n/s2n/run-ptest
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2783 aws-sdk-cpp: fix more, but not all libs building with for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
Labels: auto-backport

#2791 aws-sdk-cpp: fix more, but not all libs building with for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2792 aws-sdk-cpp: fix more, but not all libs building with for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2793 aws-sdk-cpp: fix more, but not all libs building with for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.29.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2797 Correct spelling mistake
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: auto-backport

#2799 Correct spelling mistake
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#2800 Correct spelling mistake
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#2798 Correct spelling mistake
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.582.0.bb
Labels: backport, auto-integrate, auto-created, langdale, auto-backport

#2804 2023-03-07_00-15-35_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
Labels: version-upgrade

#2801 2023-03-07_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.85.bb
Labels: version-upgrade

#2806 2023-03-07_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.85.bb
Labels: version-upgrade

#2803 2023-03-07_00-15-35_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.6.bb
Labels: version-upgrade

#2802 2023-03-07_00-15-35_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.13.bb
Labels: version-upgrade

#2805 2023-03-07_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.31.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2813 2023-03-07_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.85.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2810 2023-03-07_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.85.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2820 2023-03-07_00-15-35_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.13.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2816 2023-03-07_00-15-35_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2817 2023-03-07_00-15-35_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2818 2023-03-07_00-15-35_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.2.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2821 2023-03-07_00-15-35_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2814 2023-03-07_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.85.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2815 2023-03-07_00-15-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.85.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2811 2023-03-07_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.85.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2812 2023-03-07_00-15-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.85.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2819 2023-03-07_00-15-35_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2822 2023-03-07_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.31.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2824 2023-03-07_00-15-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.31.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2826 2023-03-08_00-14-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.86.bb
Labels: version-upgrade

#2827 2023-03-08_00-14-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.86.bb
Labels: version-upgrade

#2830 2023-03-08_00-14-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.86.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2831 2023-03-08_00-14-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.86.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2832 2023-03-08_00-14-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.86.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2828 2023-03-08_00-14-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.86.bb
Labels: version-upgrade

#2833 2023-03-08_00-14-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.86.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2834 2023-03-08_00-14-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.86.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2835 2023-03-08_00-14-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.86.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2837 2023-03-08_00-14-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.86.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2838 2023-03-08_00-14-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.86.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2836 2023-03-08_00-14-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.86.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2825 2023-03-08_00-14-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.32.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2839 2023-03-08_00-14-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.32.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2841 2023-03-08_00-14-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.32.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2840 2023-03-08_00-14-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.32.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2842 2023-03-09_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.87.bb
Labels: version-upgrade

#2845 2023-03-09_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.87.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2846 2023-03-09_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.87.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2847 2023-03-09_00-14-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.29.87.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2848 2023-03-09_00-14-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.87.bb
Labels: version-upgrade

#2849 2023-03-09_00-14-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.14.bb
Labels: version-upgrade

#2854 2023-03-09_00-14-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.14.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2851 2023-03-09_00-14-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.87.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2857 2023-03-09_00-14-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.27.87.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2855 2023-03-09_00-14-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2856 2023-03-09_00-14-34_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.8.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2852 2023-03-09_00-14-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.26.87.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale

#2844 2023-03-09_00-14-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.33.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#2861 2023-03-09_00-14-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.33.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#2860 2023-03-09_00-14-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.33.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#2862 2023-03-09_00-14-34_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.33.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, langdale
