Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-08, with the labels that each got.

#9213 2024-08-01_01-34-07_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.16.bb
Labels: version-upgrade

#9214 2024-08-01_01-34-07_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.24.bb
Labels: version-upgrade

#9216 2024-08-01_01-34-07_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9215 2024-08-01_01-34-07_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9218 2024-08-01_01-34-07_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9220 2024-08-02_01-34-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.152.bb
Labels: version-upgrade

#9221 2024-08-02_01-34-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.152.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9223 2024-08-02_01-34-17_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.33.0.bb
Labels: version-upgrade

#9225 2024-08-02_01-34-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.152.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9227 2024-08-02_01-34-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.34.bb
Labels: version-upgrade

#9228 2024-08-02_01-34-17_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.33.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9231 2024-08-02_01-34-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.34.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9224 2024-08-02_01-34-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.375.bb
Labels: version-upgrade

#9222 2024-08-02_01-34-17_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.152.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9229 2024-08-02_01-34-17_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.33.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9226 2024-08-02_01-34-17_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.152.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9230 2024-08-02_01-34-17_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.34.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9233 2024-08-02_01-34-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.375.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9232 2024-08-02_01-34-17_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.375.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9234 aws-crt-python: disable test_websocket.py unit test
  recipes-sdk/aws-crt-python/files/run-ptest
Labels: auto-backport

#9235 aws-crt-python: disable test_websocket.py unit test
  recipes-sdk/aws-crt-python/files/run-ptest
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9236 aws-crt-python: disable test_websocket.py unit test
  recipes-sdk/aws-crt-python/files/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9237 2024-08-06_01-33-36_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.5.bb
Labels: version-upgrade

#9240 2024-08-06_01-33-36_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.6.bb
Labels: version-upgrade

#9239 2024-08-06_01-33-36_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.18.bb
Labels: version-upgrade

#9242 2024-08-06_01-33-36_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.25.bb
Labels: version-upgrade

#9245 2024-08-06_01-33-36_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.25.bb
Labels: version-upgrade

#9243 2024-08-06_01-33-36_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.154.bb
Labels: version-upgrade

#9244 2024-08-06_01-33-36_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.36.bb
Labels: version-upgrade

#9241 2024-08-06_01-33-36_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.154.bb
Labels: version-upgrade

#9238 2024-08-06_01-33-36_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.377.bb
Labels: version-upgrade

#9247 2024-08-06_01-33-36_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9249 2024-08-06_01-33-36_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9255 2024-08-06_01-33-36_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9248 2024-08-06_01-33-36_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9251 2024-08-06_01-33-36_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9256 2024-08-06_01-33-36_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9262 2024-08-06_01-33-36_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.154.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9259 2024-08-06_01-33-36_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.36.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9261 2024-08-06_01-33-36_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.154.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9257 2024-08-06_01-33-36_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.154.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9258 2024-08-06_01-33-36_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.154.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9260 2024-08-06_01-33-36_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.36.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9263 2024-08-06_01-33-36_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.377.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9264 2024-08-06_01-33-36_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.377.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9250 2024-08-06_01-33-36_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9254 2024-08-06_01-33-36_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9246 2024-08-06_01-33-36_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.19.bb
Labels: version-upgrade

#9265 2024-08-06_01-33-36_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9266 2024-08-06_01-33-36_master-next_aws-c-sdkutils
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9252 2024-08-06_01-33-36_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9268 2024-08-07_01-33-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.155.bb
Labels: version-upgrade

#9269 2024-08-07_01-33-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.155.bb
Labels: version-upgrade

#9270 2024-08-07_01-33-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.37.bb
Labels: version-upgrade

#9272 2024-08-07_01-33-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.155.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9273 2024-08-07_01-33-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.155.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9275 2024-08-07_01-33-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.37.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9267 2024-08-07_01-33-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.378.bb
Labels: version-upgrade

#9271 2024-08-07_01-33-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.155.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9274 2024-08-07_01-33-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.155.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9276 2024-08-07_01-33-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.37.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9277 2024-08-07_01-33-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.378.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9278 2024-08-07_01-33-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.378.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9279 2024-08-08_01-33-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.156.bb
Labels: version-upgrade

#9280 2024-08-08_01-33-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.38.bb
Labels: version-upgrade

#9283 2024-08-08_01-33-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.156.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9282 2024-08-08_01-33-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.156.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9284 2024-08-08_01-33-45_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.7.bb
Labels: version-upgrade

#9285 2024-08-08_01-33-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.38.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9286 2024-08-08_01-33-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.38.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9287 2024-08-08_01-33-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.156.bb
Labels: version-upgrade

#9288 2024-08-08_01-33-45_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9289 2024-08-08_01-33-45_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9290 2024-08-08_01-33-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.156.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9291 2024-08-08_01-33-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.156.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9281 2024-08-08_01-33-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.379.bb
Labels: version-upgrade

#9292 2024-08-08_01-33-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.379.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9293 2024-08-08_01-33-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.379.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9295 2024-08-09_01-33-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.157.bb
Labels: version-upgrade

#9296 2024-08-09_01-33-59_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.157.bb
Labels: version-upgrade

#9297 2024-08-09_01-33-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.39.bb
Labels: version-upgrade

#9299 2024-08-09_01-33-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.157.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9301 2024-08-09_01-33-59_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.157.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9302 2024-08-09_01-33-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.39.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9294 2024-08-09_01-33-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.380.bb
Labels: version-upgrade

#9298 2024-08-09_01-33-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.157.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9300 2024-08-09_01-33-59_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.157.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9303 2024-08-09_01-33-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.39.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9305 2024-08-09_01-33-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.380.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9304 2024-08-09_01-33-59_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.380.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9306 2024-08-13_01-35-22_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.0.bb
Labels: version-upgrade

#9307 2024-08-13_01-35-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.159.bb
Labels: version-upgrade

#9310 2024-08-13_01-35-22_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.26.bb
Labels: version-upgrade

#9309 2024-08-13_01-35-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.159.bb
Labels: version-upgrade

#9312 2024-08-13_01-35-22_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.3.bb
Labels: version-upgrade

#9313 2024-08-13_01-35-22_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9311 2024-08-13_01-35-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.41.bb
Labels: version-upgrade

#9316 2024-08-13_01-35-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.159.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9321 2024-08-13_01-35-22_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9317 2024-08-13_01-35-22_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.26.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9320 2024-08-13_01-35-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.159.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9324 2024-08-13_01-35-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.41.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9308 2024-08-13_01-35-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.382.bb
Labels: version-upgrade

#9314 2024-08-13_01-35-22_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9322 2024-08-13_01-35-22_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9315 2024-08-13_01-35-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.159.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9318 2024-08-13_01-35-22_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.26.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9323 2024-08-13_01-35-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.41.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9319 2024-08-13_01-35-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.159.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9325 2024-08-13_01-35-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.382.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9326 2024-08-13_01-35-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.382.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9327 2024-08-14_01-33-51_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.27.bb
Labels: version-upgrade

#9333 2024-08-14_01-33-51_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9332 2024-08-14_01-33-51_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9329 2024-08-14_01-33-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.42.bb
Labels: version-upgrade

#9330 2024-08-14_01-33-51_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.160.bb
Labels: version-upgrade

#9331 2024-08-14_01-33-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.160.bb
Labels: version-upgrade

#9334 2024-08-14_01-33-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.42.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9335 2024-08-14_01-33-51_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.42.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9328 2024-08-14_01-33-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.383.bb
Labels: version-upgrade

#9337 2024-08-14_01-33-51_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.160.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9336 2024-08-14_01-33-51_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.160.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9339 2024-08-14_01-33-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.160.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9341 2024-08-14_01-33-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.383.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9340 2024-08-14_01-33-51_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.383.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9338 2024-08-14_01-33-51_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.160.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9342 2024-08-15_01-32-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.161.bb
Labels: version-upgrade

#9344 2024-08-15_01-32-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.161.bb
Labels: version-upgrade

#9345 2024-08-15_01-32-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.43.bb
Labels: version-upgrade

#9347 2024-08-15_01-32-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.161.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9346 2024-08-15_01-32-54_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.161.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9348 2024-08-15_01-32-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.161.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9351 2024-08-15_01-32-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.43.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9349 2024-08-15_01-32-54_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.161.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9350 2024-08-15_01-32-54_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.43.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9343 2024-08-15_01-32-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.384.bb
Labels: version-upgrade

#9353 2024-08-15_01-32-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.384.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9352 2024-08-15_01-32-54_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.384.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9354 2024-08-16_01-34-40_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.44.bb
Labels: version-upgrade

#9355 2024-08-16_01-34-40_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.162.bb
Labels: version-upgrade

#9358 2024-08-16_01-34-40_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.44.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9359 2024-08-16_01-34-40_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.44.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9357 2024-08-16_01-34-40_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.162.bb
Labels: version-upgrade

#9360 2024-08-16_01-34-40_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.162.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9361 2024-08-16_01-34-40_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.162.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9362 2024-08-16_01-34-40_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.162.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9363 2024-08-16_01-34-40_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.162.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9356 2024-08-16_01-34-40_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.385.bb
Labels: version-upgrade

#9365 2024-08-16_01-34-40_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.385.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9364 2024-08-16_01-34-40_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.385.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created
