Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-04, with the labels that each got.

#7998 2024-04-02_01-26-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.75.bb
Labels: version-upgrade

#7999 2024-04-02_01-26-30_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: version-upgrade

#8002 2024-04-02_01-26-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.75.bb
Labels: version-upgrade

#8001 2024-04-02_01-26-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.75.bb
Labels: version-upgrade

#8004 2024-04-02_01-26-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.75.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8008 2024-04-02_01-26-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.75.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8011 2024-04-02_01-26-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.75.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8007 2024-04-02_01-26-30_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8010 2024-04-02_01-26-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.75.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8003 2024-04-02_01-26-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.75.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8005 2024-04-02_01-26-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.75.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8012 2024-04-02_01-26-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.75.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8013 2024-04-02_01-26-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.75.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8006 2024-04-02_01-26-30_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8009 2024-04-02_01-26-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.75.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7997 aws-iot-client: add secure tunnel back in
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.bb
Labels: auto-backport

#8014 aws-iot-client: add secure tunnel back in
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#7996 Define RPROVIDES for corretto recipes.
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.22.7.1.bb
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
  recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: auto-backport

#8017 Define RPROVIDES for corretto recipes.
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.22.7.1.bb
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
  recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#8019 Define RPROVIDES for corretto recipes.
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.22.7.1.bb
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
  recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8021 2024-04-03_01-23-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.76.bb
Labels: version-upgrade

#8022 2024-04-03_01-23-58_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.9.bb
Labels: version-upgrade

#8026 2024-04-03_01-23-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.76.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8025 2024-04-03_01-23-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.76.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8023 2024-04-03_01-23-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.76.bb
Labels: version-upgrade

#8024 2024-04-03_01-23-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.76.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8027 2024-04-03_01-23-58_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.5.bb
Labels: version-upgrade

#8031 2024-04-03_01-23-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.76.bb
Labels: version-upgrade

#8035 2024-04-03_01-23-58_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.5.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8036 2024-04-03_01-23-58_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8032 2024-04-03_01-23-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.76.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8033 2024-04-03_01-23-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.76.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8038 2024-04-03_01-23-58_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.7.bb
Labels: version-upgrade

#8037 2024-04-03_01-23-58_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8039 2024-04-03_01-23-58_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.15.bb
Labels: version-upgrade

#8028 2024-04-03_01-23-58_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8029 2024-04-03_01-23-58_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.9.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8040 2024-04-03_01-23-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.76.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8041 2024-04-03_01-23-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.76.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8042 2024-04-03_01-23-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.76.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8043 2024-04-03_01-23-58_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8044 2024-04-03_01-23-58_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8045 2024-04-03_01-23-58_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8018 Define RPROVIDES for corretto recipes.
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.22.7.1.bb
  recipes-devtools/amazon-corretto/corretto-17-bin_17.0.10.8.1.bb
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.2.14.1.bb
  recipes-devtools/amazon-corretto/corretto-8-bin_8.402.08.1.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#8046 2024-04-03_01-23-58_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8049 2024-04-04_01-24-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.77.bb
Labels: version-upgrade

#8050 2024-04-04_01-24-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.6.bb
Labels: version-upgrade

#8051 2024-04-04_01-24-16_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.17.bb
Labels: version-upgrade

#8052 2024-04-04_01-24-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.77.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8053 2024-04-04_01-24-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.77.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8054 2024-04-04_01-24-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.77.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8055 2024-04-04_01-24-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.77.bb
Labels: version-upgrade

#8056 2024-04-04_01-24-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8060 2024-04-04_01-24-16_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8059 2024-04-04_01-24-16_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8061 2024-04-04_01-24-16_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8057 2024-04-04_01-24-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8058 2024-04-04_01-24-16_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8063 2024-04-04_01-24-16_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.11.bb
Labels: version-upgrade

#8064 2024-04-04_01-24-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.77.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8065 2024-04-04_01-24-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.77.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8066 2024-04-04_01-24-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.77.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8067 2024-04-04_01-24-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.77.bb
Labels: version-upgrade

#8068 2024-04-04_01-24-16_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8069 2024-04-04_01-24-16_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8070 2024-04-04_01-24-16_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8071 2024-04-04_01-24-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.77.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8073 2024-04-04_01-24-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.77.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8072 2024-04-04_01-24-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.77.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8074 2024-04-05_01-24-27_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.217.0.bb
Labels: version-upgrade

#8078 2024-04-05_01-24-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.78.bb
Labels: version-upgrade

#8080 2024-04-05_01-24-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.78.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8079 2024-04-05_01-24-27_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.217.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8082 2024-04-05_01-24-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.78.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8081 2024-04-05_01-24-27_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.78.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8075 2024-04-05_01-24-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.78.bb
Labels: version-upgrade

#8076 2024-04-05_01-24-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.78.bb
Labels: version-upgrade

#8086 2024-04-05_01-24-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.78.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8084 2024-04-05_01-24-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.78.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8083 2024-04-05_01-24-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.78.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8085 2024-04-05_01-24-27_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.78.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8087 2024-04-05_01-24-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.78.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8088 2024-04-05_01-24-27_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.78.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8091 2024-04-09_01-24-02_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.7.bb
Labels: version-upgrade

#8089 2024-04-09_01-24-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.80.bb
Labels: version-upgrade

#8090 2024-04-09_01-24-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.80.bb
Labels: version-upgrade

#8096 2024-04-09_01-24-02_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8093 2024-04-09_01-24-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.80.bb
Labels: version-upgrade

#8099 2024-04-09_01-24-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.80.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8102 2024-04-09_01-24-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.80.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8103 2024-04-09_01-24-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.80.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8094 2024-04-09_01-24-02_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8098 2024-04-09_01-24-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.80.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8101 2024-04-09_01-24-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.80.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8095 2024-04-09_01-24-02_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8105 2024-04-09_01-24-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.80.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8097 2024-04-09_01-24-02_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.80.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8100 2024-04-09_01-24-02_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.80.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8104 2024-04-09_01-24-02_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.80.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8106 2024-04-10_01-23-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.81.bb
Labels: version-upgrade

#8107 2024-04-10_01-23-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.81.bb
Labels: version-upgrade

#8108 2024-04-10_01-23-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.81.bb
Labels: version-upgrade

#8109 2024-04-10_01-23-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8110 2024-04-10_01-23-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.81.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8111 2024-04-10_01-23-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8113 2024-04-10_01-23-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8114 2024-04-10_01-23-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.81.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8115 2024-04-10_01-23-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8116 2024-04-10_01-23-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.81.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8117 2024-04-10_01-23-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.81.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8118 2024-04-10_01-23-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.81.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8119 2024-04-11_01-24-44_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.82.bb
Labels: version-upgrade

#8120 2024-04-11_01-24-44_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.82.bb
Labels: version-upgrade

#8121 2024-04-11_01-24-44_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.82.bb
Labels: version-upgrade

#8122 2024-04-11_01-24-44_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8123 2024-04-11_01-24-44_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8124 2024-04-11_01-24-44_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8127 2024-04-11_01-24-44_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8125 2024-04-11_01-24-44_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8126 2024-04-11_01-24-44_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8129 2024-04-11_01-24-44_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.10.bb
Labels: version-upgrade

#8130 2024-04-11_01-24-44_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.82.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8131 2024-04-11_01-24-44_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.82.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8132 2024-04-11_01-24-44_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.82.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8133 2024-04-11_01-24-44_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
Labels: version-upgrade

#8134 2024-04-11_01-24-44_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8137 2024-04-11_01-24-44_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8138 2024-04-11_01-24-44_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8139 2024-04-11_01-24-44_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8135 2024-04-11_01-24-44_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.10.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8136 2024-04-11_01-24-44_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8140 2024-04-12_01-25-08_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.7.bb
Labels: version-upgrade

#8147 2024-04-12_01-25-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.24.0.bb
Labels: version-upgrade

#8149 2024-04-12_01-25-08_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8150 2024-04-12_01-25-08_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.7.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8148 2024-04-12_01-25-08_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8151 2024-04-12_01-25-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.24.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8152 2024-04-12_01-25-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.24.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8153 2024-04-12_01-25-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.24.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8143 2024-04-12_01-25-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.83.bb
Labels: version-upgrade

#8146 2024-04-12_01-25-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.83.bb
Labels: version-upgrade

#8145 2024-04-12_01-25-08_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.11.bb
Labels: version-upgrade

#8144 2024-04-12_01-25-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.83.bb
Labels: version-upgrade

#8155 2024-04-12_01-25-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8157 2024-04-12_01-25-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.83.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8158 2024-04-12_01-25-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8156 2024-04-12_01-25-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.83.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#8160 2024-04-12_01-25-08_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8163 2024-04-12_01-25-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.83.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#8164 2024-04-12_01-25-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.83.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created
