Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-01, with the labels that each got.

#6832 2024-01-02_01-26-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.11.bb
Labels: version-upgrade

#6835 2024-01-02_01-26-49_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.10.bb
Labels: version-upgrade

#6833 2024-01-02_01-26-49_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.12.bb
Labels: version-upgrade

#6836 2024-01-02_01-26-49_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.0.bb
Labels: version-upgrade

#6841 2024-01-02_01-26-49_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.19.bb
Labels: version-upgrade

#6845 2024-01-02_01-26-49_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6846 2024-01-02_01-26-49_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6843 2024-01-02_01-26-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6840 2024-01-02_01-26-49_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.0.bb
Labels: version-upgrade

#6854 2024-01-02_01-26-49_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6849 2024-01-02_01-26-49_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6851 2024-01-02_01-26-49_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6848 2024-01-02_01-26-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.11.bb
Labels: version-upgrade

#6838 2024-01-02_01-26-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.0.bb
Labels: version-upgrade

#6852 2024-01-02_01-26-49_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6844 2024-01-02_01-26-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6839 2024-01-02_01-26-49_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.0.bb
Labels: version-upgrade

#6856 2024-01-02_01-26-49_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6857 2024-01-02_01-26-49_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6859 2024-01-02_01-26-49_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.4.9.bb
Labels: version-upgrade

#6837 2024-01-02_01-26-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.11.bb
Labels: version-upgrade

#6860 2024-01-02_01-26-49_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6861 2024-01-02_01-26-49_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6864 2024-01-02_01-26-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6867 2024-01-02_01-26-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6865 2024-01-02_01-26-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6869 2024-01-02_01-26-49_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6873 2024-01-02_01-26-49_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.4.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6874 2024-01-02_01-26-49_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.4.9.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6868 2024-01-02_01-26-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6877 2024-01-02_01-26-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6871 2024-01-02_01-26-49_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6875 2024-01-02_01-26-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6842 2024-01-02_01-26-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6850 2024-01-02_01-26-49_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.12.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6847 2024-01-02_01-26-49_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.10.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6853 2024-01-02_01-26-49_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6858 2024-01-02_01-26-49_master-next_aws-c-iot
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.19.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6863 2024-01-02_01-26-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6862 2024-01-02_01-26-49_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6866 2024-01-02_01-26-49_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6876 2024-01-02_01-26-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6872 2024-01-02_01-26-49_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.4.9.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6870 2024-01-02_01-26-49_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6855 2024-01-02_01-26-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.235.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#6879 2024-01-02_01-26-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.235.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6880 2024-01-02_01-26-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.235.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6878 2024-01-02_01-26-49_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.235.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6834 2024-01-02_01-26-49_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.1.bb
Labels: version-upgrade

#6883 2024-01-02_01-26-49_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6881 2024-01-02_01-26-49_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6882 2024-01-02_01-26-49_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6885 aws-iot-securetunneling-localproxy: fix GCC 13 build
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
Labels: auto-backport

#6886 aws-iot-securetunneling-localproxy: fix GCC 13 build
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#6887 aws-iot-securetunneling-localproxy: fix GCC 13 build
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6893 2024-01-09_10-33-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.11.bb
Labels: version-upgrade

#6897 2024-01-09_10-33-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.15.bb
Labels: version-upgrade

#6890 2024-01-09_10-33-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.15.bb
Labels: version-upgrade

#6894 2024-01-09_10-33-31_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.1.bb
Labels: version-upgrade

#6896 2024-01-09_10-33-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.15.bb
Labels: version-upgrade

#6898 2024-01-09_10-33-31_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.2.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6892 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.0.bb
Labels: version-upgrade

#6901 2024-01-09_10-33-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6895 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.0.bb
Labels: version-upgrade

#6911 2024-01-09_10-33-31_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6891 2024-01-09_10-33-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.239.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#6919 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6908 2024-01-09_10-33-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6913 2024-01-09_10-33-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6915 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6909 2024-01-09_10-33-31_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6907 2024-01-09_10-33-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.15.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6912 2024-01-09_10-33-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.15.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6918 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6902 2024-01-09_10-33-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.11.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6904 2024-01-09_10-33-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.15.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6900 2024-01-09_10-33-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6899 2024-01-09_10-33-31_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.2.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6920 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6903 2024-01-09_10-33-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6906 2024-01-09_10-33-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6917 2024-01-09_10-33-31_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6924 firecracker-bin, jailer-bin, greengrass-bin: simplify LICENSE path to…
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: auto-backport

#6922 2024-01-09_10-33-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.239.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6921 2024-01-09_10-33-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.239.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6914 2024-01-09_10-33-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6910 2024-01-09_10-33-31_master-next_aws-c-event-stream
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6927 aws-iot-securetunneling-localproxy: remove setting of cxx-standard
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: auto-backport

#6925 firecracker-bin, jailer-bin, greengrass-bin: simplify LICENSE path to…
  recipes-containers/firecracker-bin/firecracker-bin_1.3.3.bb
  recipes-containers/firecracker-bin/jailer-bin_1.3.3.bb
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.9.6.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6929 aws-iot-securetunneling-localproxy: remove setting of cxx-standard
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6923 2024-01-09_10-33-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.239.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6930 aws-iot-fleetwise-edge: remove setting of cxx-standard
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.0.bb
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
Labels: auto-backport

#6931 aws-iot-fleetwise-edge: remove setting of cxx-standard
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.0.bb
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#6932 aws-iot-fleetwise-edge: remove setting of cxx-standard
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.0.bb
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6888 corretto-21-bin: add recipe.
  recipes-devtools/amazon-corretto/corretto-21-bin/run-ptest
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.1.12.1.bb
Labels: auto-backport

#6934 corretto-21-bin: add recipe.
  recipes-devtools/amazon-corretto/corretto-21-bin/run-ptest
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.1.12.1.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#6935 corretto-21-bin: add recipe.
  recipes-devtools/amazon-corretto/corretto-21-bin/run-ptest
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.1.12.1.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#6933 corretto-21-bin: add recipe.
  recipes-devtools/amazon-corretto/corretto-21-bin/run-ptest
  recipes-devtools/amazon-corretto/corretto-21-bin_21.0.1.12.1.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6936 2024-01-11_01-27-09_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.20.0.bb
Labels: version-upgrade

#6937 2024-01-11_01-27-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.16.bb
Labels: version-upgrade

#6940 2024-01-11_01-27-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.16.bb
Labels: version-upgrade

#6938 2024-01-11_01-27-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.240.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#6941 2024-01-11_01-27-09_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.20.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6944 2024-01-11_01-27-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6947 2024-01-11_01-27-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6942 2024-01-11_01-27-09_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.20.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6943 2024-01-11_01-27-09_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.20.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6948 2024-01-11_01-27-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6946 2024-01-11_01-27-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6945 2024-01-11_01-27-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6949 2024-01-11_01-27-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6952 2024-01-11_01-27-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.240.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6950 2024-01-11_01-27-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.240.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6951 2024-01-11_01-27-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.240.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6939 2024-01-11_01-27-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.16.bb
Labels: version-upgrade

#6953 2024-01-11_01-27-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.16.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6954 2024-01-11_01-27-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6955 2024-01-11_01-27-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6956 2024-01-12_01-27-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.17.bb
Labels: version-upgrade

#6957 2024-01-12_01-27-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.17.bb
Labels: version-upgrade

#6958 2024-01-12_01-27-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.17.bb
Labels: version-upgrade

#6959 2024-01-12_01-27-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6960 2024-01-12_01-27-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6961 2024-01-12_01-27-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6962 2024-01-12_01-27-10_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.1.bb
Labels: version-upgrade

#6964 2024-01-12_01-27-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6963 2024-01-12_01-27-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6965 2024-01-12_01-27-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6966 2024-01-12_01-27-10_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.1.bb
Labels: version-upgrade

#6969 2024-01-12_01-27-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.17.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6967 2024-01-12_01-27-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6968 2024-01-12_01-27-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6972 2024-01-12_01-27-10_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6971 2024-01-12_01-27-10_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6973 2024-01-12_01-27-10_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6974 2024-01-12_01-27-10_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.1.bb
Labels: version-upgrade

#6975 2024-01-12_01-27-10_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6976 2024-01-12_01-27-10_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6977 2024-01-12_01-27-10_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6978 2024-01-12_01-27-10_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6979 2024-01-12_01-27-10_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6980 2024-01-12_01-27-10_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6970 2024-01-12_01-27-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.241.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#6982 2024-01-12_01-27-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.241.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#6983 2024-01-12_01-27-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.241.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#6981 2024-01-12_01-27-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.241.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#6984 add new recipe aws-cli-v2
  recipes-devtools/python/python3-jmespath_%.bbappend
  recipes-devtools/python/python3-ruamel-yaml-clib_0.2.7.bb
  recipes-devtools/python/python3-urllib3-1.x_1.26.18.bb
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.13.bb
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.2.bb
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2/run-ptest
  recipes-support/aws-cli-v2/aws-cli-v2_2.15.9.bb
Labels: auto-backport

#6986 add new recipe aws-cli-v2
  recipes-devtools/python/python3-jmespath_%.bbappend
  recipes-devtools/python/python3-ruamel-yaml-clib_0.2.7.bb
  recipes-devtools/python/python3-urllib3-1.x_1.26.18.bb
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.13.bb
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.2.bb
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2/run-ptest
  recipes-support/aws-cli-v2/aws-cli-v2_2.15.9.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#6988 amazon-ssm-agent: override VERSION to match actual version.
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.2086.0.bb
Labels: auto-backport

#6990 amazon-ssm-agent: override VERSION to match actual version.
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.1041.0.bb_broken
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport
