Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-09, with the labels that each got.

#9456 corretto-11-bin: fix arm version
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.24.8.1.bb
Labels: auto-backport

#9458 corretto-11-bin: fix arm version
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.24.8.1.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9457 corretto-11-bin: fix arm version
  recipes-devtools/amazon-corretto/corretto-11-bin_11.0.24.8.1.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9459 aws-sdk-cpp: build everything for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.395.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9460 aws-sdk-cpp: build everything for arm32
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.395.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9462 2024-09-03_01-35-03_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.859.0.bb
Labels: version-upgrade

#9464 2024-09-03_01-35-03_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.28.2.bb
Labels: version-upgrade

#9465 2024-09-03_01-35-03_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.859.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9467 2024-09-03_01-35-03_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.28.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9468 2024-09-03_01-35-03_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.28.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9463 2024-09-03_01-35-03_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.396.bb
Labels: version-upgrade

#9469 2024-09-03_01-35-03_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.396.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9470 2024-09-03_01-35-03_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.396.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9472 2024-09-04_01-34-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.27.bb
Labels: version-upgrade

#9471 2024-09-04_01-34-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.11.bb
Labels: version-upgrade

#9475 2024-09-04_01-34-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.11.bb
Labels: version-upgrade

#9474 2024-09-04_01-34-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.11.bb
Labels: version-upgrade

#9473 2024-09-04_01-34-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.397.bb
Labels: version-upgrade

#9476 2024-09-04_01-34-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.27.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9477 2024-09-04_01-34-26_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.27.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9480 2024-09-04_01-34-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9479 2024-09-04_01-34-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9478 2024-09-04_01-34-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9483 2024-09-04_01-34-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9482 2024-09-04_01-34-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9485 2024-09-04_01-34-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.397.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9484 2024-09-04_01-34-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.397.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9481 2024-09-04_01-34-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9487 2024-09-05_01-34-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.5.bb
Labels: version-upgrade

#9491 2024-09-05_01-34-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9492 2024-09-05_01-34-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9488 2024-09-05_01-34-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.12.bb
Labels: version-upgrade

#9486 2024-09-05_01-34-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.12.bb
Labels: version-upgrade

#9489 2024-09-05_01-34-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.12.bb
Labels: version-upgrade

#9494 2024-09-05_01-34-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9495 2024-09-05_01-34-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9496 2024-09-05_01-34-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9497 2024-09-05_01-34-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9498 2024-09-05_01-34-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9490 2024-09-05_01-34-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.398.bb
Labels: version-upgrade

#9500 2024-09-05_01-34-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.398.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9499 2024-09-05_01-34-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.398.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9505 2024-09-06_01-34-28_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.19.bb
Labels: version-upgrade

#9503 2024-09-06_01-34-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.13.bb
Labels: version-upgrade

#9502 2024-09-06_01-34-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.13.bb
Labels: version-upgrade

#9506 2024-09-06_01-34-28_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.28.bb
Labels: version-upgrade

#9509 2024-09-06_01-34-28_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9510 2024-09-06_01-34-28_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9514 2024-09-06_01-34-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9515 2024-09-06_01-34-28_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.28.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9513 2024-09-06_01-34-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9511 2024-09-06_01-34-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9512 2024-09-06_01-34-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9507 2024-09-06_01-34-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.13.bb
Labels: version-upgrade

#9508 2024-09-06_01-34-28_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.4.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#9516 2024-09-06_01-34-28_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.28.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9504 2024-09-06_01-34-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.399.bb
Labels: version-upgrade

#9518 2024-09-06_01-34-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9517 2024-09-06_01-34-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9519 2024-09-06_01-34-28_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.4.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9520 2024-09-06_01-34-28_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.4.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9522 2024-09-06_01-34-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.399.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9521 2024-09-06_01-34-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.399.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9523 greengrass-bin: fix fleetprovisioning
  recipes-iot/aws-iot-greengrass/files/claim.cert.pem
  recipes-iot/aws-iot-greengrass/files/claim.pkey.pem
  recipes-iot/aws-iot-greengrass/files/claim.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: auto-backport

#9526 greengrass-bin: point fleetprovisioning plugin to 1.2.1
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: auto-backport

#9527 greengrass-bin: point fleetprovisioning plugin to 1.2.1
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9525 greengrass-bin: fix fleetprovisioning
  recipes-iot/aws-iot-greengrass/files/claim.cert.pem
  recipes-iot/aws-iot-greengrass/files/claim.pkey.pem
  recipes-iot/aws-iot-greengrass/files/claim.root.pem
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: backport, auto-created, auto-backport, scarthgap

#9528 greengrass-bin: point fleetprovisioning plugin to 1.2.1
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9529 2024-09-10_01-35-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.15.bb
Labels: version-upgrade

#9530 2024-09-10_01-35-25_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.29.bb
Labels: version-upgrade

#9531 2024-09-10_01-35-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.2.bb
Labels: version-upgrade

#9538 2024-09-10_01-35-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.28.bb
Labels: version-upgrade

#9532 2024-09-10_01-35-25_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#9533 2024-09-10_01-35-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.15.bb
Labels: version-upgrade

#9543 2024-09-10_01-35-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.28.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9539 2024-09-10_01-35-25_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.29.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9534 2024-09-10_01-35-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.15.bb
Labels: version-upgrade

#9537 2024-09-10_01-35-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9546 2024-09-10_01-35-25_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9542 2024-09-10_01-35-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9547 2024-09-10_01-35-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9550 2024-09-10_01-35-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.15.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9535 2024-09-10_01-35-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.401.bb
Labels: version-upgrade

#9540 2024-09-10_01-35-25_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.29.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9541 2024-09-10_01-35-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9536 2024-09-10_01-35-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9544 2024-09-10_01-35-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.28.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9545 2024-09-10_01-35-25_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9548 2024-09-10_01-35-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9549 2024-09-10_01-35-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.15.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9551 2024-09-10_01-35-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.401.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9552 2024-09-10_01-35-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.401.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9553 2024-09-11_01-35-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.9.bb
Labels: version-upgrade

#9554 2024-09-11_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.16.bb
Labels: version-upgrade

#9556 2024-09-11_01-35-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.9.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9555 2024-09-11_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.16.bb
Labels: version-upgrade

#9557 2024-09-11_01-35-07_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9558 2024-09-11_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.16.bb
Labels: version-upgrade

#9560 2024-09-11_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9561 2024-09-11_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9563 2024-09-11_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9564 2024-09-11_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9565 2024-09-11_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9562 2024-09-11_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9559 2024-09-11_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.402.bb
Labels: version-upgrade

#9567 2024-09-11_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.402.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9566 2024-09-11_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.402.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9568 README.md: update copyright year
  README.md
Labels: auto-backport

#9569 README.md: update copyright year
  README.md
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9570 README.md: update copyright year
  README.md
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9571 2024-09-12_01-34-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.17.bb
Labels: version-upgrade

#9572 2024-09-12_01-34-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.17.bb
Labels: version-upgrade

#9573 2024-09-12_01-34-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.17.bb
Labels: version-upgrade

#9575 2024-09-12_01-34-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9574 2024-09-12_01-34-19_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.403.bb
Labels: version-upgrade

#9578 2024-09-12_01-34-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9579 2024-09-12_01-34-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9577 2024-09-12_01-34-19_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9576 2024-09-12_01-34-19_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9580 2024-09-12_01-34-19_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9581 2024-09-12_01-34-19_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.403.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9582 2024-09-12_01-34-19_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.403.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9583 2024-09-13_01-34-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.5.bb
Labels: version-upgrade

#9586 2024-09-13_01-34-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9587 2024-09-13_01-34-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.18.bb
Labels: version-upgrade

#9585 2024-09-13_01-34-31_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9588 2024-09-13_01-34-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.30.bb
Labels: version-upgrade

#9589 2024-09-13_01-34-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.18.bb
Labels: version-upgrade

#9590 2024-09-13_01-34-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9591 2024-09-13_01-34-31_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9593 2024-09-13_01-34-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.30.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9594 2024-09-13_01-34-31_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.30.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9592 2024-09-13_01-34-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.18.bb
Labels: version-upgrade

#9595 2024-09-13_01-34-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9596 2024-09-13_01-34-31_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9597 2024-09-13_01-34-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9598 2024-09-13_01-34-31_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9584 2024-09-13_01-34-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.404.bb
Labels: version-upgrade

#9599 2024-09-13_01-34-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.404.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9600 2024-09-13_01-34-31_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.404.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9601 aws-iot-securetunneling-localproxy: re-enable recipe
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/gcc13_2.patch
Labels: auto-backport

#9606 2024-09-17_01-29-46_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.20.bb
Labels: version-upgrade

#9604 2024-09-17_01-29-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.20.bb
Labels: version-upgrade

#9607 2024-09-17_01-29-46_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.31.bb
Labels: version-upgrade

#9605 2024-09-17_01-29-46_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.20.bb
Labels: version-upgrade

#9609 2024-09-17_01-29-46_master-next_aws-checksums
  recipes-sdk/aws-checksums/aws-checksums_0.1.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9612 2024-09-17_01-29-46_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9613 2024-09-17_01-29-46_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.10.bb
Labels: version-upgrade

#9614 2024-09-17_01-29-46_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9618 2024-09-17_01-29-46_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.28.3.bb
Labels: version-upgrade
