Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-03, with the labels that each got.

#7634 2024-03-01_01-27-22_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.3.bb
Labels: version-upgrade

#7636 2024-03-01_01-27-22_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.3.bb
Labels: version-upgrade

#7639 2024-03-01_01-27-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.53.bb
Labels: version-upgrade

#7640 2024-03-01_01-27-22_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.1.bb
Labels: version-upgrade

#7635 2024-03-01_01-27-22_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#7643 2024-03-01_01-27-22_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7645 2024-03-01_01-27-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.53.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7648 2024-03-01_01-27-22_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7652 2024-03-01_01-27-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.53.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7646 2024-03-01_01-27-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.53.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7647 2024-03-01_01-27-22_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.53.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7649 2024-03-01_01-27-22_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7644 2024-03-01_01-27-22_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7650 2024-03-01_01-27-22_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7651 2024-03-01_01-27-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.53.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7653 2024-03-01_01-27-22_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.53.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7655 2024-03-01_01-27-22_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7658 2024-03-01_01-27-22_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7657 2024-03-01_01-27-22_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.5.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7638 2024-03-01_01-27-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.53.bb
Labels: version-upgrade

#7659 2024-03-01_01-27-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.53.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7660 2024-03-01_01-27-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.53.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7661 2024-03-01_01-27-22_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.53.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7637 2024-03-01_01-27-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.276.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7662 2024-03-01_01-27-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.276.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7663 2024-03-01_01-27-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.276.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7664 2024-03-01_01-27-22_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.276.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7656 2024-03-01_01-27-22_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7654 2024-03-01_01-27-22_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.1.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7642 2024-03-01_01-27-22_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.3.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7641 2024-03-01_01-27-22_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.15.24.bb
Labels: version-upgrade

#7665 2024-03-01_01-27-22_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.15.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7666 s2n: enable more ptests
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.4.5.bb
Labels: auto-backport

#7667 s2n: enable more ptests
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.4.5.bb
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#7668 s2n: enable more ptests
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.4.5.bb
Labels: backport, dunfell, auto-integrate, auto-created, auto-backport

#7669 s2n: enable more ptests
  recipes-sdk/s2n/s2n/run-ptest
  recipes-sdk/s2n/s2n_1.4.5.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#7672 2024-03-05_01-22-26_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.2.bb
Labels: version-upgrade

#7671 2024-03-05_01-22-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.55.bb
Labels: version-upgrade

#7673 2024-03-05_01-22-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.55.bb
Labels: version-upgrade

#7674 2024-03-05_01-22-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.55.bb
Labels: version-upgrade

#7670 2024-03-05_01-22-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.278.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7675 2024-03-05_01-22-26_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.2.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7678 2024-03-05_01-22-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.55.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7682 2024-03-05_01-22-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.55.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7676 2024-03-05_01-22-26_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7684 2024-03-05_01-22-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.55.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7677 2024-03-05_01-22-26_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7679 2024-03-05_01-22-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.55.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7685 2024-03-05_01-22-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.55.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7680 2024-03-05_01-22-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.55.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7681 2024-03-05_01-22-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.55.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7683 2024-03-05_01-22-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.55.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7686 2024-03-05_01-22-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.55.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7689 2024-03-05_01-22-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.278.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7687 2024-03-05_01-22-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.278.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7688 2024-03-05_01-22-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.278.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7692 2024-03-06_01-22-58_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.131.0.bb
Labels: version-upgrade

#7690 2024-03-06_01-22-58_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.14.bb
Labels: version-upgrade

#7694 2024-03-06_01-22-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.22.0.bb
Labels: version-upgrade

#7691 2024-03-06_01-22-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.56.bb
Labels: version-upgrade

#7697 2024-03-06_01-22-58_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.131.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7699 2024-03-06_01-22-58_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7700 2024-03-06_01-22-58_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7695 2024-03-06_01-22-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.56.bb
Labels: version-upgrade

#7705 2024-03-06_01-22-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.56.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7701 2024-03-06_01-22-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.22.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7703 2024-03-06_01-22-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.22.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7702 2024-03-06_01-22-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.22.0.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7704 2024-03-06_01-22-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.56.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7706 2024-03-06_01-22-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.56.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7696 2024-03-06_01-22-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.56.bb
Labels: version-upgrade

#7707 2024-03-06_01-22-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.56.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7708 2024-03-06_01-22-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.56.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7709 2024-03-06_01-22-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.56.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7712 2024-03-06_01-22-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.56.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7710 2024-03-06_01-22-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.56.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7711 2024-03-06_01-22-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.56.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7693 2024-03-06_01-22-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.279.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7715 2024-03-06_01-22-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.279.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7713 2024-03-06_01-22-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.279.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7714 2024-03-06_01-22-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.279.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7716 2024-03-07_01-14-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.57.bb
Labels: version-upgrade

#7719 2024-03-07_01-14-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.57.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7721 2024-03-07_01-14-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.57.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7720 2024-03-07_01-14-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.57.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7722 2024-03-07_01-14-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.57.bb
Labels: version-upgrade

#7723 2024-03-07_01-14-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.57.bb
Labels: version-upgrade

#7724 2024-03-07_01-14-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.57.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7725 2024-03-07_01-14-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.57.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7726 2024-03-07_01-14-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.57.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7727 2024-03-07_01-14-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.57.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7728 2024-03-07_01-14-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.57.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7729 2024-03-07_01-14-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.57.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7718 2024-03-07_01-14-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.280.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7732 2024-03-07_01-14-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.280.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7730 2024-03-07_01-14-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.280.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7731 2024-03-07_01-14-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.280.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7717 2024-03-07_01-14-26_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.15.26.bb
Labels: version-upgrade

#7734 2024-03-08_01-22-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.58.bb
Labels: version-upgrade

#7736 2024-03-08_01-22-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.58.bb
Labels: version-upgrade

#7737 2024-03-08_01-22-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.58.bb
Labels: version-upgrade

#7739 2024-03-08_01-22-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7742 2024-03-08_01-22-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7743 2024-03-08_01-22-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7740 2024-03-08_01-22-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7746 2024-03-08_01-22-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.58.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7735 2024-03-08_01-22-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.281.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7745 2024-03-08_01-22-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.58.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7738 2024-03-08_01-22-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7741 2024-03-08_01-22-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7744 2024-03-08_01-22-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.58.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7749 2024-03-08_01-22-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.281.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7747 2024-03-08_01-22-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.281.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7748 2024-03-08_01-22-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.281.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7753 aws-iot-securetunneling-localproxy: boost 1.84 format include missing
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
Labels: auto-backport

#7755 aws-iot-securetunneling-localproxy: boost 1.84 format include missing
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#7754 aws-iot-securetunneling-localproxy: boost 1.84 format include missing
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
Labels: backport, auto-integrate, auto-created, auto-backport, nanbield

#7758 2024-03-12_01-23-09_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.6.bb
Labels: version-upgrade

#7756 2024-03-12_01-23-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.60.bb
Labels: version-upgrade

#7759 2024-03-12_01-23-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.60.bb
Labels: version-upgrade

#7760 2024-03-12_01-23-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.60.bb
Labels: version-upgrade

#7763 2024-03-12_01-23-09_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7764 2024-03-12_01-23-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.60.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7766 2024-03-12_01-23-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7767 2024-03-12_01-23-09_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.6.bb
Labels: version-upgrade

#7769 2024-03-12_01-23-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7772 2024-03-12_01-23-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.60.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7762 2024-03-12_01-23-09_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7773 2024-03-12_01-23-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.60.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7776 2024-03-12_01-23-09_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7774 2024-03-12_01-23-09_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7765 2024-03-12_01-23-09_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7757 2024-03-12_01-23-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.283.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#7768 2024-03-12_01-23-09_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7761 2024-03-12_01-23-09_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7775 2024-03-12_01-23-09_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.6.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7777 2024-03-12_01-23-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.283.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7779 2024-03-12_01-23-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.283.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7778 2024-03-12_01-23-09_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.283.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7771 2024-03-12_01-23-09_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.60.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7780 2024-03-13_01-24-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.61.bb
Labels: version-upgrade

#7782 2024-03-13_01-24-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.61.bb
Labels: version-upgrade

#7783 2024-03-13_01-24-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7785 2024-03-13_01-24-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7786 2024-03-13_01-24-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.61.bb
Labels: version-upgrade

#7788 2024-03-13_01-24-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield

#7789 2024-03-13_01-24-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.61.bb
Labels: version-upgrade, backport, dunfell, auto-integrate, auto-created

#7790 2024-03-13_01-24-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7792 2024-03-13_01-24-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.61.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#7793 2024-03-13_01-24-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, nanbield
