Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-07, with the labels that each got.

#8920 2024-07-02_01-33-01_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.0.bb
Labels: version-upgrade

#8921 2024-07-02_01-33-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.31.0.bb
Labels: version-upgrade

#8919 2024-07-02_01-33-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.137.bb
Labels: version-upgrade

#8923 2024-07-02_01-33-01_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.137.bb
Labels: version-upgrade

#8924 2024-07-02_01-33-01_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.17.bb
Labels: version-upgrade

#8922 2024-07-02_01-33-01_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.19.bb
Labels: version-upgrade

#8918 2024-07-02_01-33-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.360.bb
Labels: version-upgrade

#8926 2024-07-02_01-33-01_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8927 2024-07-02_01-33-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.31.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8925 2024-07-02_01-33-01_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8928 2024-07-02_01-33-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.31.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8935 2024-07-02_01-33-01_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8933 2024-07-02_01-33-01_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.17.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8932 2024-07-02_01-33-01_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.137.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8936 2024-07-02_01-33-01_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8931 2024-07-02_01-33-01_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.137.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8930 2024-07-02_01-33-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.137.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8934 2024-07-02_01-33-01_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.17.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8929 2024-07-02_01-33-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.137.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8938 2024-07-02_01-33-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.360.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8937 2024-07-02_01-33-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.360.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8939 2024-07-03_01-33-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.138.bb
Labels: version-upgrade

#8940 2024-07-03_01-33-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.138.bb
Labels: version-upgrade

#8941 2024-07-03_01-33-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.20.bb
Labels: version-upgrade

#8943 2024-07-03_01-33-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.138.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8944 2024-07-03_01-33-30_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.138.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8945 2024-07-03_01-33-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.138.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8946 2024-07-03_01-33-30_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.138.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8947 2024-07-03_01-33-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8948 2024-07-03_01-33-30_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8942 2024-07-03_01-33-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.361.bb
Labels: version-upgrade

#8949 2024-07-03_01-33-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.361.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8950 2024-07-03_01-33-30_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.361.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8951 2024-07-04_01-33-04_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
Labels: version-upgrade

#8952 2024-07-04_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.21.bb
Labels: version-upgrade

#8954 2024-07-04_01-33-04_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8953 2024-07-04_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.139.bb
Labels: version-upgrade

#8958 2024-07-04_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8959 2024-07-04_01-33-04_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.2.bb
Labels: version-upgrade

#8960 2024-07-04_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.139.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8962 2024-07-04_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.139.bb
Labels: version-upgrade

#8963 2024-07-04_01-33-04_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#8965 2024-07-04_01-33-04_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8967 2024-07-04_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.139.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8969 2024-07-04_01-33-04_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8955 2024-07-04_01-33-04_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8956 2024-07-04_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.362.bb
Labels: version-upgrade

#8964 2024-07-04_01-33-04_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8957 2024-07-04_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8966 2024-07-04_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.139.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8968 2024-07-04_01-33-04_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8970 2024-07-04_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.362.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8971 2024-07-04_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.362.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8961 2024-07-04_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.139.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8972 greengrass set jvm java 11default
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: auto-backport

#8973 greengrass set jvm java 11default
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8974 greengrass set jvm java 11default
  recipes-iot/aws-iot-greengrass/greengrass-bin_2.12.6.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8976 2024-07-09_01-33-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.23.bb
Labels: version-upgrade

#8977 2024-07-09_01-33-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.141.bb
Labels: version-upgrade

#8978 2024-07-09_01-33-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.141.bb
Labels: version-upgrade

#8979 2024-07-09_01-33-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.23.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8975 2024-07-09_01-33-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.364.bb
Labels: version-upgrade

#8982 2024-07-09_01-33-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.141.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8984 2024-07-09_01-33-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.141.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8980 2024-07-09_01-33-18_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.23.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8981 2024-07-09_01-33-18_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.141.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8983 2024-07-09_01-33-18_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.141.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8986 2024-07-09_01-33-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.364.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8985 2024-07-09_01-33-18_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.364.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8989 2024-07-10_01-33-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.142.bb
Labels: version-upgrade

#8991 2024-07-10_01-33-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.24.bb
Labels: version-upgrade

#8994 2024-07-10_01-33-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.142.bb
Labels: version-upgrade

#8990 2024-07-10_01-33-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.365.bb
Labels: version-upgrade

#8992 2024-07-10_01-33-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.142.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8998 2024-07-10_01-33-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.142.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8993 2024-07-10_01-33-28_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.142.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8995 2024-07-10_01-33-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.24.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8997 2024-07-10_01-33-28_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.142.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8996 2024-07-10_01-33-28_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.24.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9000 2024-07-10_01-33-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.365.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8999 2024-07-10_01-33-28_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.365.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9001 2024-07-11_01-33-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.25.bb
Labels: version-upgrade

#9002 2024-07-11_01-33-25_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.10.bb
Labels: version-upgrade

#9004 2024-07-11_01-33-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.25.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9005 2024-07-11_01-33-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.25.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9008 2024-07-11_01-33-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.143.bb
Labels: version-upgrade

#9006 2024-07-11_01-33-25_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9007 2024-07-11_01-33-25_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9009 2024-07-11_01-33-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.143.bb
Labels: version-upgrade

#9010 2024-07-11_01-33-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.143.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9011 2024-07-11_01-33-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.143.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9012 2024-07-11_01-33-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.143.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9013 2024-07-11_01-33-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.143.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9003 2024-07-11_01-33-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.366.bb
Labels: version-upgrade

#9015 2024-07-11_01-33-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.366.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9014 2024-07-11_01-33-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.366.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8988 add aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: auto-backport

#9016 add aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9017 add aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9018 2024-07-12_01-33-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
Labels: version-upgrade

#9022 2024-07-12_01-33-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9020 2024-07-12_01-33-13_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.3.bb
Labels: version-upgrade

#9021 2024-07-12_01-33-13_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9023 2024-07-12_01-33-13_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
Labels: version-upgrade

#9025 2024-07-12_01-33-13_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9026 2024-07-12_01-33-13_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9028 2024-07-12_01-33-13_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9027 2024-07-12_01-33-13_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9029 aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning: fix ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
Labels: auto-backport

#9030 aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning: fix ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9031 aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning: fix ptest
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning/run-ptest
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9019 2024-07-12_01-33-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
Labels: version-upgrade

#9033 2024-07-12_01-33-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9032 2024-07-12_01-33-13_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9034 aws-iot-device-sdk-cpp-v2-samples*: suppress QA error
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
Labels: auto-backport

#9036 aws-iot-device-sdk-cpp-v2-samples*: suppress QA error
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9035 aws-iot-device-sdk-cpp-v2-samples*: suppress QA error
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-fleet-provisoning.bb
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-samples-mqtt5-pubsub.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9037 suppress QA errors *-ptest: buildpaths
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
  recipes-sdk/aws-c-common/aws-c-common_0.9.23.bb
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.18.bb
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.2.bb
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.21.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.4.bb
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.16.bb
  recipes-sdk/aws-checksums/aws-checksums_0.1.18.bb
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
Labels: auto-backport

#9038 suppress QA errors *-ptest: buildpaths
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
  recipes-sdk/aws-c-common/aws-c-common_0.9.23.bb
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.18.bb
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.2.bb
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.21.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.4.bb
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.16.bb
  recipes-sdk/aws-checksums/aws-checksums_0.1.18.bb
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9039 suppress QA errors *-ptest: buildpaths
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.2.bb
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.9.1.bb
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
  recipes-sdk/aws-c-cal/aws-c-cal_0.7.1.bb
  recipes-sdk/aws-c-common/aws-c-common_0.9.23.bb
  recipes-sdk/aws-c-compression/aws-c-compression_0.2.18.bb
  recipes-sdk/aws-c-event-stream/aws-c-event-stream_0.4.2.bb
  recipes-sdk/aws-c-http/aws-c-http_0.8.3.bb
  recipes-sdk/aws-c-io/aws-c-io_0.14.11.bb
  recipes-sdk/aws-c-iot/aws-c-iot_0.1.21.bb
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.4.bb
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.1.bb
  recipes-sdk/aws-c-sdkutils/aws-c-sdkutils_0.1.16.bb
  recipes-sdk/aws-checksums/aws-checksums_0.1.18.bb
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.2.2143.0.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#9040 amazon-kvs-webrtc-sdk, amazon-ssm-agent: suppress QA errors
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
Labels: auto-backport

#9042 amazon-kvs-webrtc-sdk, amazon-ssm-agent: suppress QA errors
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.551.0.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9044 2024-07-16_01-33-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.4.bb
Labels: version-upgrade

#9047 2024-07-16_01-33-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9043 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.22.0.bb
Labels: version-upgrade

#9048 2024-07-16_01-33-34_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9049 2024-07-16_01-33-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.4.bb
Labels: version-upgrade

#9045 2024-07-16_01-33-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.26.bb
Labels: version-upgrade

#9050 2024-07-16_01-33-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.13.bb
Labels: version-upgrade

#9052 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.22.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9051 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-python-v2
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.22.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9046 2024-07-16_01-33-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.144.bb
Labels: version-upgrade

#9054 2024-07-16_01-33-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.4.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9053 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.33.0.bb
Labels: version-upgrade

#9055 2024-07-16_01-33-34_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.6.4.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9056 2024-07-16_01-33-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.26.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9059 2024-07-16_01-33-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9060 2024-07-16_01-33-34_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9057 2024-07-16_01-33-34_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.26.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9058 2024-07-16_01-33-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.144.bb
Labels: version-upgrade

#9061 2024-07-16_01-33-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.144.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9062 2024-07-16_01-33-34_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.144.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9063 2024-07-16_01-33-34_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.2.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#9064 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.33.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9065 2024-07-16_01-33-34_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.33.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9066 2024-07-16_01-33-34_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.27.4.bb
Labels: version-upgrade

#9067 2024-07-16_01-33-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.144.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9068 2024-07-16_01-33-34_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.144.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9070 2024-07-16_01-33-34_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.2.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9071 2024-07-16_01-33-34_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.21.2.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created
