Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-10, with the labels that each got.

#9748 2024-10-01_01-35-26_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.36.0.bb
Labels: version-upgrade

#9747 2024-10-01_01-35-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.29.bb
Labels: version-upgrade

#9746 2024-10-01_01-35-26_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.61.bb
Labels: version-upgrade

#9751 2024-10-01_01-35-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.29.bb
Labels: version-upgrade

#9750 2024-10-01_01-35-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.29.bb
Labels: version-upgrade

#9749 2024-10-01_01-35-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.416.bb
Labels: version-upgrade

#9752 2024-10-01_01-35-26_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.36.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9753 2024-10-01_01-35-26_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.36.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9754 2024-10-01_01-35-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.29.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9758 2024-10-01_01-35-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.29.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9755 2024-10-01_01-35-26_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.29.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9760 2024-10-01_01-35-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.29.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9757 2024-10-01_01-35-26_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.29.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9756 2024-10-01_01-35-26_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.61.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9759 2024-10-01_01-35-26_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.29.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9762 2024-10-01_01-35-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.416.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9761 2024-10-01_01-35-26_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.416.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9763 backport-based-on-label.yml: add styhead
  .github/workflows/backport-based-on-label.yml
Labels: auto-backport

#9766 [Backport styhead-next] backport-based-on-label.yml: add styhead
  .github/workflows/backport-based-on-label.yml
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#9765 backport-based-on-label.yml: add styhead
  .github/workflows/backport-based-on-label.yml
Labels: backport, auto-integrate, auto-created, auto-backport, styhead

#9767 2024-10-02_01-35-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade

#9773 2024-10-02_01-35-16_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.22.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#9768 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade

#9775 2024-10-02_01-35-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9776 2024-10-02_01-35-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9769 2024-10-02_01-35-16_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.63.bb
Labels: version-upgrade

#9777 2024-10-02_01-35-16_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.22.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9778 2024-10-02_01-35-16_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.22.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9770 2024-10-02_01-35-16_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.987.0.bb
Labels: version-upgrade

#9780 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9782 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9771 2024-10-02_01-35-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.31.bb
Labels: version-upgrade

#9784 2024-10-02_01-35-16_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.63.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9789 [Backport kirkstone-next] 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9788 2024-10-02_01-35-16_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.987.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9793 2024-10-02_01-35-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.31.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9792 2024-10-02_01-35-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9772 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade

#9798 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9797 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#9800 [Backport kirkstone-next] 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9802 gh workflows auto-backport, backport-based-on-label
  .github/workflows/auto-approve-and-enable-auto-merge.yml
  .github/workflows/auto-backport.yml
  .github/workflows/backport-based-on-label.yml
Labels: auto-backport

#9801 [Backport styhead-next] 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9799 2024-10-02_01-35-16_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.417.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, styhead

#9796 [Backport styhead-next] 2024-10-02_01-35-16_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9795 [Backport styhead-next] 2024-10-02_01-35-16_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.987.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9794 [Backport styhead-next] 2024-10-02_01-35-16_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.63.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9790 [Backport styhead-next] 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9787 2024-10-02_01-35-16_master-next_amazon-ssm-agent
  recipes-devtools/python/python3-botocore_1.35.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, styhead

#9786 [Backport styhead-next] 2024-10-02_01-35-16_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.22.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9785 2024-10-02_01-35-16_master-next_aws-cli-v2
  recipes-sdk/aws-crt-python/aws-crt-python_0.22.0.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, styhead

#9783 [Backport styhead-next] 2024-10-02_01-35-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#9781 2024-10-02_01-35-16_master-next_python3-botocore
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, styhead

#9774 2024-10-02_01-35-16_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.31.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, styhead

#9807 2024-10-03_01-35-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.32.bb
Labels: version-upgrade

#9806 2024-10-03_01-35-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.418.bb
Labels: version-upgrade

#9805 2024-10-03_01-35-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.32.bb
Labels: version-upgrade

#9804 2024-10-03_01-35-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.32.bb
Labels: version-upgrade

#9803 2024-10-03_01-35-48_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.64.bb
Labels: version-upgrade

#9826 2024-10-04_01-34-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.419.bb
Labels: version-upgrade

#9825 2024-10-04_01-34-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.36.1.bb
Labels: version-upgrade

#9824 2024-10-04_01-34-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.33.bb
Labels: version-upgrade

#9823 2024-10-04_01-34-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.33.bb
Labels: version-upgrade

#9822 2024-10-04_01-34-58_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.33.bb
Labels: version-upgrade

#9820 2024-10-04_01-34-58_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.4.bb
Labels: version-upgrade

#9808 [Backport kirkstone-next] 2024-10-03_01-35-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.32.bb
Labels: version-upgrade

#9809 [Backport scarthgap-next] 2024-10-03_01-35-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.32.bb
Labels: version-upgrade

#9810 [Backport styhead-next] 2024-10-03_01-35-48_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.32.bb
Labels: version-upgrade

#9811 [Backport kirkstone-next] 2024-10-03_01-35-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.418.bb
Labels: version-upgrade

#9812 [Backport scarthgap-next] 2024-10-03_01-35-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.418.bb
Labels: version-upgrade

#9813 [Backport styhead-next] 2024-10-03_01-35-48_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.418.bb
Labels: version-upgrade

#9814 [Backport kirkstone-next] 2024-10-03_01-35-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.32.bb
Labels: version-upgrade

#9815 [Backport scarthgap-next] 2024-10-03_01-35-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.32.bb
Labels: version-upgrade

#9816 [Backport styhead-next] 2024-10-03_01-35-48_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.32.bb
Labels: version-upgrade

#9817 [Backport kirkstone-next] 2024-10-03_01-35-48_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.34.32.bb
Labels: version-upgrade

#9818 [Backport scarthgap-next] 2024-10-03_01-35-48_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.64.bb
Labels: version-upgrade

#9819 [Backport styhead-next] 2024-10-03_01-35-48_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.17.64.bb
Labels: version-upgrade

#9828 gh actions: set fixed versions, use of gh auto merge
  .github/workflows/auto-approve-and-enable-auto-merge.yml
  .github/workflows/ff-merge.yml
  .github/workflows/pr-cve-check.yml
Labels: auto-backport

#9836 2024-10-08_01-35-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.35.bb
Labels: version-upgrade

#9835 2024-10-08_01-35-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.1.bb
Labels: version-upgrade

#9834 2024-10-08_01-35-04_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.7.bb
Labels: version-upgrade

#9833 2024-10-08_01-35-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.35.bb
Labels: version-upgrade

#9832 2024-10-08_01-35-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.421.bb
Labels: version-upgrade

#9831 2024-10-08_01-35-04_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.1.bb
Labels: version-upgrade

#9839 [Backport scarthgap-next] 2024-10-08_01-35-04_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.7.bb
Labels: version-upgrade

#9840 [Backport styhead-next] 2024-10-08_01-35-04_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.7.bb
Labels: version-upgrade

#9841 [Backport scarthgap-next] 2024-10-08_01-35-04_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.1.bb
Labels: version-upgrade

#9842 [Backport styhead-next] 2024-10-08_01-35-04_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.1.bb
Labels: version-upgrade

#9838 [Backport kirkstone-next] 2024-10-08_01-35-04_master-next_aws-c-mqtt
  recipes-sdk/aws-c-mqtt/aws-c-mqtt_0.10.7.bb
Labels: version-upgrade

#9850 2024-10-09_01-35-15_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.36.bb
Labels: version-upgrade

#9853 [Backport kirkstone-next] 2024-10-09_01-35-15_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.36.bb
Labels: version-upgrade

#9849 2024-10-09_01-35-15_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.2.bb
Labels: version-upgrade

#9848 2024-10-09_01-35-15_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.422.bb
Labels: version-upgrade

#9846 2024-10-09_01-35-15_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.36.bb
Labels: version-upgrade

#9847 2024-10-09_01-35-15_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.10.3.bb
Labels: version-upgrade

#9858 [Backport kirkstone-next] 2024-10-09_01-35-15_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.2.bb
Labels: version-upgrade

#9867 [Backport kirkstone-next] 2024-10-09_01-35-15_master-next_python3-s3transfer
  recipes-devtools/python/python3-s3transfer_0.10.3.bb
Labels: version-upgrade

#9864 [Backport kirkstone-next] 2024-10-09_01-35-15_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.36.bb
Labels: version-upgrade

#9854 [Backport scarthgap-next] 2024-10-09_01-35-15_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.36.bb
Labels: version-upgrade

#9855 [Backport styhead-next] 2024-10-09_01-35-15_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.36.bb
Labels: version-upgrade

#9859 [Backport scarthgap-next] 2024-10-09_01-35-15_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.2.bb
Labels: version-upgrade

#9865 [Backport scarthgap-next] 2024-10-09_01-35-15_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.36.bb
Labels: version-upgrade

#9866 [Backport styhead-next] 2024-10-09_01-35-15_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.36.bb
Labels: version-upgrade

#9861 [Backport styhead-next] 2024-10-09_01-35-15_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.2.bb
Labels: version-upgrade

#9860 [Backport kirkstone-next] 2024-10-09_01-35-15_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.422.bb
Labels: version-upgrade

#9863 [Backport styhead-next] 2024-10-09_01-35-15_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.422.bb
Labels: version-upgrade

#9862 [Backport scarthgap-next] 2024-10-09_01-35-15_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.422.bb
Labels: version-upgrade

#9868 2024-10-10_01-35-07_master-next_s2n
  recipes-sdk/s2n/s2n_1.5.5.bb
Labels: version-upgrade

#9869 2024-10-10_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.3.bb
Labels: version-upgrade

#9871 2024-10-10_01-35-07_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.3.bb
Labels: version-upgrade

#9872 [Backport kirkstone-next] 2024-10-10_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.3.bb
Labels: version-upgrade

#9873 [Backport scarthgap-next] 2024-10-10_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.3.bb
Labels: version-upgrade

#9874 [Backport styhead-next] 2024-10-10_01-35-07_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.3.bb
Labels: version-upgrade

#9870 2024-10-10_01-35-07_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: version-upgrade

#9876 2024-10-10_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.37.bb
Labels: version-upgrade

#9879 2024-10-10_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.37.bb
Labels: version-upgrade

#9877 [Backport scarthgap-next] 2024-10-10_01-35-07_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.3.bb
Labels: version-upgrade

#9878 [Backport styhead-next] 2024-10-10_01-35-07_master-next_aws-cli-v2
  recipes-support/aws-cli-v2/aws-cli-v2/0001-remove_exact_python_version_requirements.patch
  recipes-support/aws-cli-v2/aws-cli-v2_2.18.3.bb
Labels: version-upgrade

#9881 [Backport kirkstone-next] 2024-10-10_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.37.bb
Labels: version-upgrade

#9882 [Backport scarthgap-next] 2024-10-10_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.37.bb
Labels: version-upgrade

#9883 [Backport styhead-next] 2024-10-10_01-35-07_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.37.bb
Labels: version-upgrade

#9884 [Backport kirkstone-next] 2024-10-10_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.37.bb
Labels: version-upgrade

#9885 [Backport scarthgap-next] 2024-10-10_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.37.bb
Labels: version-upgrade

#9886 [Backport styhead-next] 2024-10-10_01-35-07_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.37.bb
Labels: version-upgrade

#9880 [Backport styhead-next] 2024-10-10_01-35-07_master-next_aws-iot-securetunneling-localproxy
  recipes-iot/aws-iot-securetunneling-localproxy/aws-iot-securetunneling-localproxy_git.bb
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-support-any.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
Labels: version-upgrade

#9875 2024-10-10_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.423.bb
Labels: version-upgrade

#9888 [Backport scarthgap-next] 2024-10-10_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.423.bb
Labels: version-upgrade

#9889 [Backport styhead-next] 2024-10-10_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.423.bb
Labels: version-upgrade

#9887 [Backport kirkstone-next] 2024-10-10_01-35-07_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.423.bb
Labels: version-upgrade

#9890 2024-10-11_01-35-35_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.19.bb
Labels: version-upgrade

#9891 2024-10-11_01-35-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.38.bb
Labels: version-upgrade

#9892 2024-10-11_01-35-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.38.bb
Labels: version-upgrade

#9897 [Backport kirkstone-next] 2024-10-11_01-35-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.38.bb
Labels: version-upgrade

#9898 [Backport scarthgap-next] 2024-10-11_01-35-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.38.bb
Labels: version-upgrade

#9899 [Backport styhead-next] 2024-10-11_01-35-35_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.35.38.bb
Labels: version-upgrade

#9901 [Backport kirkstone-next] 2024-10-11_01-35-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.38.bb
Labels: version-upgrade

#9902 [Backport scarthgap-next] 2024-10-11_01-35-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.38.bb
Labels: version-upgrade

#9903 [Backport styhead-next] 2024-10-11_01-35-35_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.35.38.bb
Labels: version-upgrade

#9905 2024-10-11_01-35-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.4.bb
Labels: version-upgrade

#9906 2024-10-11_01-35-35_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.5.bb
Labels: version-upgrade

#9907 [Backport kirkstone-next] 2024-10-11_01-35-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.4.bb
Labels: version-upgrade

#9908 [Backport scarthgap-next] 2024-10-11_01-35-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.4.bb
Labels: version-upgrade

#9909 [Backport styhead-next] 2024-10-11_01-35-35_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.35.4.bb
Labels: version-upgrade

#9910 [Backport kirkstone-next] 2024-10-11_01-35-35_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.5.bb
Labels: version-upgrade

#9911 [Backport scarthgap-next] 2024-10-11_01-35-35_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.5.bb
Labels: version-upgrade

#9912 [Backport styhead-next] 2024-10-11_01-35-35_master-next_aws-iot-device-client
  recipes-iot/aws-iot-device-client/aws-iot-device-client_1.9.5.bb
Labels: version-upgrade

#9904 2024-10-11_01-35-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.424.bb
Labels: version-upgrade

#9914 [Backport scarthgap-next] 2024-10-11_01-35-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.424.bb
Labels: version-upgrade

#9915 [Backport styhead-next] 2024-10-11_01-35-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.424.bb
Labels: version-upgrade

#9913 [Backport kirkstone-next] 2024-10-11_01-35-35_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.424.bb
Labels: version-upgrade
