Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-06, with the labels that each got.

#8652 2024-06-04_01-32-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: version-upgrade

#8654 2024-06-04_01-32-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.10.bb
Labels: version-upgrade

#8658 2024-06-04_01-32-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8653 2024-06-04_01-32-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.118.bb
Labels: version-upgrade

#8655 2024-06-04_01-32-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.118.bb
Labels: version-upgrade

#8661 2024-06-04_01-32-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8657 2024-06-04_01-32-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.0.bb
Labels: version-upgrade

#8662 2024-06-04_01-32-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.118.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8664 2024-06-04_01-32-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.118.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8666 2024-06-04_01-32-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8656 2024-06-04_01-32-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.341.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8659 2024-06-04_01-32-32_master-next_aws-iot-device-sdk-cpp-v2
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2-version.inc
  recipes-sdk/aws-iot-device-sdk-cpp-v2/aws-iot-device-sdk-cpp-v2_1.32.7.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8660 2024-06-04_01-32-32_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8663 2024-06-04_01-32-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.118.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8667 2024-06-04_01-32-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8665 2024-06-04_01-32-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.118.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8668 2024-06-04_01-32-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.341.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8669 2024-06-04_01-32-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.341.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8670 2024-06-05_01-32-38_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.20.bb
Labels: version-upgrade

#8672 2024-06-05_01-32-38_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.119.bb
Labels: version-upgrade

#8675 2024-06-05_01-32-38_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.2.bb
Labels: version-upgrade

#8676 2024-06-05_01-32-38_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.9.bb
Labels: version-upgrade

#8678 2024-06-05_01-32-38_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8673 2024-06-05_01-32-38_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.1.bb
Labels: version-upgrade

#8677 2024-06-05_01-32-38_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8674 2024-06-05_01-32-38_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.119.bb
Labels: version-upgrade

#8680 2024-06-05_01-32-38_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.119.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8682 2024-06-05_01-32-38_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8683 2024-06-05_01-32-38_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8684 2024-06-05_01-32-38_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.9.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8681 2024-06-05_01-32-38_master-next_aws-c-http
  recipes-sdk/aws-c-http/aws-c-http_0.8.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8686 2024-06-05_01-32-38_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.1.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8671 2024-06-05_01-32-38_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.342.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8685 2024-06-05_01-32-38_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.1.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8687 2024-06-05_01-32-38_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.119.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8688 2024-06-05_01-32-38_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.119.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8689 2024-06-05_01-32-38_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.342.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8690 2024-06-05_01-32-38_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.342.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8679 2024-06-05_01-32-38_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.119.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8692 2024-06-06_01-32-10_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.21.bb
Labels: version-upgrade

#8695 2024-06-06_01-32-10_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.16.bb
Labels: version-upgrade

#8693 2024-06-06_01-32-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.120.bb
Labels: version-upgrade

#8694 2024-06-06_01-32-10_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.11.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#8696 2024-06-06_01-32-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.120.bb
Labels: version-upgrade

#8697 2024-06-06_01-32-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.2.bb
Labels: version-upgrade

#8691 2024-06-06_01-32-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.343.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8699 2024-06-06_01-32-10_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8705 2024-06-06_01-32-10_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.11.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8701 2024-06-06_01-32-10_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.16.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8698 2024-06-06_01-32-10_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8706 2024-06-06_01-32-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.120.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8700 2024-06-06_01-32-10_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.16.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8704 2024-06-06_01-32-10_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.11.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8707 2024-06-06_01-32-10_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.120.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8703 2024-06-06_01-32-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.120.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8708 2024-06-06_01-32-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.2.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8702 2024-06-06_01-32-10_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.120.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8709 2024-06-06_01-32-10_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8711 2024-06-06_01-32-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.343.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8710 2024-06-06_01-32-10_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.343.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8712 2024-06-07_01-33-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.3.bb
Labels: version-upgrade

#8714 2024-06-07_01-33-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.121.bb
Labels: version-upgrade

#8716 2024-06-07_01-33-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.3.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8717 2024-06-07_01-33-05_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.3.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8715 2024-06-07_01-33-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.121.bb
Labels: version-upgrade

#8719 2024-06-07_01-33-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.121.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8718 2024-06-07_01-33-05_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.121.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8720 2024-06-07_01-33-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.121.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8713 2024-06-07_01-33-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.344.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8721 2024-06-07_01-33-05_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.121.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8722 2024-06-07_01-33-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.344.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8723 2024-06-07_01-33-05_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.344.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8727 2024-06-11_01-33-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.29.0.bb
Labels: version-upgrade

#8724 2024-06-11_01-33-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.5.bb
Labels: version-upgrade

#8725 2024-06-11_01-33-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.123.bb
Labels: version-upgrade

#8729 2024-06-11_01-33-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.29.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8728 2024-06-11_01-33-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.123.bb
Labels: version-upgrade

#8730 2024-06-11_01-33-08_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.29.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8732 2024-06-11_01-33-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.5.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8734 2024-06-11_01-33-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.123.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8731 2024-06-11_01-33-08_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.5.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8733 2024-06-11_01-33-08_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.123.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8735 2024-06-11_01-33-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.123.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8736 2024-06-11_01-33-08_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.123.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8726 2024-06-11_01-33-08_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.346.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8738 2024-06-11_01-33-08_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.346.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8737 2024-06-11_01-33-08_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.346.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8739 2024-06-12_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.6.bb
Labels: version-upgrade

#8740 2024-06-12_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.124.bb
Labels: version-upgrade

#8742 2024-06-12_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.6.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8743 2024-06-12_01-33-04_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.6.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8745 2024-06-12_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.124.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8744 2024-06-12_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.124.bb
Labels: version-upgrade

#8746 2024-06-12_01-33-04_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.124.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8747 2024-06-12_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.124.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8748 2024-06-12_01-33-04_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.124.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8741 2024-06-12_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8750 2024-06-12_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8749 2024-06-12_01-33-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8751 2024-06-13_01-32-42_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.12.bb
Labels: version-upgrade

#8757 2024-06-13_01-32-42_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.12.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8756 2024-06-13_01-32-42_master-next_aws-crt-cpp
  recipes-sdk/aws-crt-cpp/aws-crt-cpp_0.26.12.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8752 2024-06-13_01-32-42_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.7.bb
Labels: version-upgrade

#8753 2024-06-13_01-32-42_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.125.bb
Labels: version-upgrade

#8754 2024-06-13_01-32-42_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.125.bb
Labels: version-upgrade

#8755 2024-06-13_01-32-42_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.12.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade

#8758 2024-06-13_01-32-42_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.7.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8760 2024-06-13_01-32-42_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.125.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8761 2024-06-13_01-32-42_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.125.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8763 2024-06-13_01-32-42_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.125.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8764 2024-06-13_01-32-42_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.12.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8765 2024-06-13_01-32-42_master-next_aws-crt-python
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.12.bb
  recipes-sdk/aws-crt-python/files/fix-shared-linking.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8762 2024-06-13_01-32-42_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.125.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8766 2024-06-14_01-32-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.126.bb
Labels: version-upgrade

#8767 2024-06-14_01-32-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.126.bb
Labels: version-upgrade

#8769 2024-06-14_01-32-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.126.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8770 2024-06-14_01-32-49_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.126.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8768 2024-06-14_01-32-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.8.bb
Labels: version-upgrade

#8771 2024-06-14_01-32-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.126.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8772 2024-06-14_01-32-49_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.126.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8774 2024-06-14_01-32-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8773 2024-06-14_01-32-49_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8776 Add example to help and check for correct AMI_DISK_SIZE_GB
  scripts/ec2-ami/create-ec2-ami.sh
Labels: auto-backport

#8777 Add example to help and check for correct AMI_DISK_SIZE_GB
  scripts/ec2-ami/create-ec2-ami.sh
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8780 aws-iot-fleetwise, aws-iot-securetunneling-localproxy, aws-sdk-cpp: F…
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: auto-backport

#8782 aws-iot-fleetwise, aws-iot-securetunneling-localproxy, aws-sdk-cpp: F…
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8781 aws-iot-fleetwise, aws-iot-securetunneling-localproxy, aws-sdk-cpp: F…
  recipes-iot/aws-iot-fleetwise/files/remove-cxx-standard.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/boost-include-format.patch
  recipes-iot/aws-iot-securetunneling-localproxy/files/remove-cxx-standard.patch
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8783 amazon-kvs-producer-sdk-cpp: Fix patch status string
  recipes-sdk/amazon-kvs-producer-sdk/amazon-kvs-producer-sdk-cpp/amazon-kvs-producer-sdk-cpp-deps.patch
Labels: auto-backport

#8786 aws-sdk-cpp: Remove patch and fix cmake module dir
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: auto-backport

#8788 aws-sdk-cpp: Remove patch and fix cmake module dir
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8789 aws-sdk-cpp: Remove patch and fix cmake module dir
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.347.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8794 2024-06-18_01-33-06_master-next_python3-urllib3-1.x
  recipes-devtools/python/python3-urllib3-1.x_1.26.19.bb
Labels: version-upgrade

#8793 2024-06-18_01-33-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.128.bb
Labels: version-upgrade

#8795 2024-06-18_01-33-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.10.bb
Labels: version-upgrade

#8796 2024-06-18_01-33-06_master-next_python3-urllib3-1.x
  recipes-devtools/python/python3-urllib3-1.x_1.26.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8792 2024-06-18_01-33-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.351.bb
Labels: version-upgrade

#8800 2024-06-18_01-33-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.10.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8798 2024-06-18_01-33-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.128.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8797 2024-06-18_01-33-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.128.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8799 2024-06-18_01-33-06_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.33.10.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8802 2024-06-18_01-33-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.351.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8801 2024-06-18_01-33-06_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.351.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8787 aws-iot-fleetwise-edge: Fix boost filesystem extension deprication
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.1.bb
  recipes-iot/aws-iot-fleetwise/files/boost_filesystem_extension.patch
Labels: auto-backport

#8791 2024-06-18_01-33-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.128.bb
Labels: version-upgrade

#8805 2024-06-18_01-33-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.128.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8806 2024-06-18_01-33-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.128.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8803 aws-iot-fleetwise-edge: Fix boost filesystem extension deprication
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.1.bb
  recipes-iot/aws-iot-fleetwise/files/boost_filesystem_extension.patch
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8804 aws-iot-fleetwise-edge: Fix boost filesystem extension deprication
  recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge_1.1.1.bb
  recipes-iot/aws-iot-fleetwise/files/boost_filesystem_extension.patch
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8810 2024-06-19_01-33-06_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.129.bb
Labels: version-upgrade

#8811 2024-06-19_01-33-06_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.129.bb
Labels: version-upgrade
