Repository aws4embeddedlinux/meta-aws, pull requests merged in 2024-05, with the labels that each got.

#8383 2024-05-01_01-32-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.95.bb
Labels: version-upgrade

#8385 2024-05-01_01-32-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.95.bb
Labels: version-upgrade

#8386 2024-05-01_01-32-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.95.bb
Labels: version-upgrade

#8384 2024-05-01_01-32-39_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.318.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8394 2024-05-02_01-29-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.96.bb
Labels: version-upgrade

#8395 2024-05-02_01-29-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.13.bb
Labels: version-upgrade

#8396 2024-05-02_01-29-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.96.bb
Labels: version-upgrade

#8397 2024-05-02_01-29-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.96.bb
Labels: version-upgrade

#8400 2024-05-02_01-29-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8399 2024-05-02_01-29-25_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8398 2024-05-02_01-29-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.319.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8387 2024-05-01_01-32-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.95.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8389 2024-05-01_01-32-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.95.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8390 2024-05-01_01-32-39_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.95.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8388 2024-05-01_01-32-39_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.95.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8391 2024-05-01_01-32-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.95.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8392 2024-05-01_01-32-39_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.95.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8401 aws-sdk-cpp: use cmake instead of cmake-qemu
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.319.bb
Labels: auto-backport

#8402 aws-sdk-cpp: use cmake instead of cmake-qemu
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.318.bb
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8405 2024-05-03_01-31-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.26.0.bb
Labels: version-upgrade

#8406 2024-05-03_01-31-01_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.418.0.bb
Labels: version-upgrade

#8407 2024-05-03_01-31-01_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.97.bb
Labels: version-upgrade

#8410 2024-05-03_01-31-01_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.97.bb
Labels: version-upgrade

#8409 2024-05-03_01-31-01_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.97.bb
Labels: version-upgrade

#8408 2024-05-03_01-31-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.320.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8411 2024-05-03_01-31-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.26.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8413 2024-05-03_01-31-01_master-next_amazon-ssm-agent
  recipes-support/amazon-ssm-agent/amazon-ssm-agent_3.3.418.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8412 2024-05-03_01-31-01_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.26.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8414 2024-05-03_01-31-01_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.320.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8416 2024-05-07_01-30-29_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.99.bb
Labels: version-upgrade

#8417 2024-05-07_01-30-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.8.bb
Labels: version-upgrade

#8419 2024-05-07_01-30-29_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.99.bb
Labels: version-upgrade

#8422 2024-05-07_01-30-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.8.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8420 2024-05-07_01-30-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.19.bb
Labels: version-upgrade

#8418 2024-05-07_01-30-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.322.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8425 2024-05-07_01-30-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8423 2024-05-07_01-30-29_master-next_aws-c-io
  recipes-sdk/aws-c-io/aws-c-io_0.14.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8424 2024-05-07_01-30-29_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8427 2024-05-07_01-30-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.322.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8426 2024-05-07_01-30-29_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.322.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8430 2024-05-08_01-20-44_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.100.bb
Labels: version-upgrade

#8431 2024-05-08_01-20-44_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.100.bb
Labels: version-upgrade

#8432 2024-05-08_01-20-44_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.100.bb
Labels: version-upgrade

#8429 2024-05-08_01-20-44_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.323.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8434 2024-05-08_01-20-44_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.323.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8433 2024-05-08_01-20-44_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.323.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8428 2024-05-08_01-20-44_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.8.bb
Labels: version-upgrade

#8438 2024-05-08_01-20-44_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.8.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8439 2024-05-09_01-30-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.101.bb
Labels: version-upgrade

#8441 2024-05-09_01-30-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.18.bb
Labels: version-upgrade

#8442 2024-05-09_01-30-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.101.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8443 2024-05-09_01-30-25_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.101.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8447 2024-05-09_01-30-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.18.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8446 2024-05-09_01-30-25_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.18.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8445 2024-05-09_01-30-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.101.bb
Labels: version-upgrade

#8448 2024-05-09_01-30-25_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.13.bb
Labels: version-upgrade

#8449 2024-05-09_01-30-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.101.bb
Labels: version-upgrade

#8453 2024-05-09_01-30-25_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.13.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8450 2024-05-09_01-30-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.101.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8452 2024-05-09_01-30-25_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.13.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8451 2024-05-09_01-30-25_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.101.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8455 2024-05-09_01-30-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.101.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8454 2024-05-09_01-30-25_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.101.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8440 2024-05-09_01-30-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.324.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8444 2024-05-09_01-30-25_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
Labels: version-upgrade

#8456 2024-05-09_01-30-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.324.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8457 2024-05-09_01-30-25_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.324.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8458 2024-05-09_01-30-25_master-next_amazon-kvs-webrtc-sdk
  recipes-sdk/amazon-kvs-webrtc-sdk/amazon-kvs-webrtc-sdk_1.10.2.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8459 2024-05-10_01-31-04_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.20.bb
Labels: version-upgrade

#8461 2024-05-10_01-31-04_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.20.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8460 2024-05-10_01-31-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.325.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8462 2024-05-10_01-31-04_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.20.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8464 2024-05-10_01-31-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.325.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8463 2024-05-10_01-31-04_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.325.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8465 EC2-AMI feature: fix race, get var
  conf/machine/aws-ec2-arm64.conf
  scripts/ec2-ami/create-ec2-ami.sh
Labels: auto-backport

#8466 EC2-AMI feature: fix race, get var
  conf/machine/aws-ec2-arm64.conf
  scripts/ec2-ami/create-ec2-ami.sh
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8467 EC2-AMI feature: fix race, get var
  conf/machine/aws-ec2-arm64.conf
  scripts/ec2-ami/create-ec2-ami.sh
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8470 2024-05-14_01-30-45_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.14.bb
Labels: version-upgrade

#8469 2024-05-14_01-30-45_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.19.bb
Labels: version-upgrade

#8468 2024-05-14_01-30-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.104.bb
Labels: version-upgrade

#8476 2024-05-14_01-30-45_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.14.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8474 2024-05-14_01-30-45_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.21.bb
Labels: version-upgrade

#8478 2024-05-14_01-30-45_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.19.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8479 2024-05-14_01-30-45_master-next_aws-c-common
  recipes-sdk/aws-c-common/aws-c-common_0.9.19.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8472 2024-05-14_01-30-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.104.bb
Labels: version-upgrade

#8475 2024-05-14_01-30-45_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.9.bb
Labels: version-upgrade

#8473 2024-05-14_01-30-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.104.bb
Labels: version-upgrade

#8477 2024-05-14_01-30-45_master-next_s2n
  recipes-sdk/s2n/s2n_1.4.14.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8482 2024-05-14_01-30-45_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.21.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8483 2024-05-14_01-30-45_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.21.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8486 2024-05-14_01-30-45_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.9.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8487 2024-05-14_01-30-45_master-next_aws-c-s3
  recipes-sdk/aws-c-s3/aws-c-s3_0.5.9.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8480 2024-05-14_01-30-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.104.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8481 2024-05-14_01-30-45_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.104.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8471 2024-05-14_01-30-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.327.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8488 2024-05-14_01-30-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.104.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8484 2024-05-14_01-30-45_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.104.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8489 2024-05-14_01-30-45_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.104.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8491 2024-05-14_01-30-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.327.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8490 2024-05-14_01-30-45_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.327.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8494 2024-05-15_01-31-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.105.bb
Labels: version-upgrade

#8496 2024-05-15_01-31-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.105.bb
Labels: version-upgrade

#8495 2024-05-15_01-31-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.105.bb
Labels: version-upgrade

#8493 2024-05-15_01-31-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.328.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8498 2024-05-15_01-31-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.105.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8497 2024-05-15_01-31-32_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8499 2024-05-15_01-31-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.105.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8502 2024-05-15_01-31-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.105.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8500 2024-05-15_01-31-32_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8501 2024-05-15_01-31-32_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.105.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8503 2024-05-15_01-31-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.328.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8504 2024-05-15_01-31-32_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.328.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8507 2024-05-16_01-30-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.27.0.bb
Labels: version-upgrade

#8508 2024-05-16_01-30-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.106.bb
Labels: version-upgrade

#8509 2024-05-16_01-30-58_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
Labels: version-upgrade

#8510 2024-05-16_01-30-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.27.0.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8514 2024-05-16_01-30-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.106.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8516 2024-05-16_01-30-58_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8511 2024-05-16_01-30-58_master-next_aws-lc
  recipes-sdk/aws-lc/aws-lc_1.27.0.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8512 2024-05-16_01-30-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.329.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8515 2024-05-16_01-30-58_master-next_aws-c-auth
  recipes-sdk/aws-c-auth/aws-c-auth_0.7.22.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8513 2024-05-16_01-30-58_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.106.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8518 2024-05-16_01-30-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.329.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8517 2024-05-16_01-30-58_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.329.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8506 2024-05-16_01-30-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.106.bb
Labels: version-upgrade

#8519 2024-05-16_01-30-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.106.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8520 2024-05-16_01-30-58_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.106.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8521 2024-05-17_01-31-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.107.bb
Labels: version-upgrade

#8523 2024-05-17_01-31-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.107.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8524 2024-05-17_01-31-52_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8525 2024-05-17_01-31-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.107.bb
Labels: version-upgrade

#8522 2024-05-17_01-31-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.330.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade

#8530 2024-05-17_01-31-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.330.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8529 2024-05-17_01-31-52_master-next_aws-sdk-cpp
  recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.330.bb
  recipes-sdk/aws-sdk-cpp/files/0002-build-fix-building-without-external-dependencies.patch
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8527 2024-05-17_01-31-52_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8526 2024-05-17_01-31-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.107.bb
Labels: version-upgrade

#8532 2024-05-17_01-31-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.107.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8531 2024-05-17_01-31-52_master-next_python3-botocore
  recipes-devtools/python/python3-botocore_1.34.107.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8533 README.md: remove agl platinum membership image
  README.md
  images/agl-member-plat.png
Labels: auto-backport

#8535 README.md: remove agl platinum membership image
  README.md
  images/agl-member-plat.png
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8534 README.md: remove agl platinum membership image
  README.md
  images/agl-member-plat.png
Labels: backport, auto-integrate, auto-created, auto-backport, scarthgap

#8538 aws-crt-python, aws-iot-device-sdk-python-v2: add proper versioning
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.9.bb
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.4.bb
Labels: auto-backport

#8539 aws-crt-python, aws-iot-device-sdk-python-v2: add proper versioning
  recipes-sdk/aws-crt-python/aws-crt-python_0.20.9.bb
  recipes-sdk/aws-iot-device-sdk-python-v2/aws-iot-device-sdk-python-v2_1.21.4.bb
Labels: backport, kirkstone, auto-integrate, auto-created, auto-backport

#8541 2024-05-21_01-30-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.109.bb
Labels: version-upgrade

#8542 2024-05-21_01-30-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.109.bb
Labels: version-upgrade

#8543 2024-05-21_01-30-59_master-next_aws-c-cal
  recipes-sdk/aws-c-cal/aws-c-cal_0.6.14.bb
Labels: version-upgrade

#8544 2024-05-21_01-30-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.109.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8545 2024-05-21_01-30-59_master-next_python3-boto3
  recipes-devtools/python/python3-boto3_1.34.109.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap

#8547 2024-05-21_01-30-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.109.bb
Labels: version-upgrade, backport, kirkstone, auto-integrate, auto-created

#8548 2024-05-21_01-30-59_master-next_aws-cli
  recipes-support/aws-cli/aws-cli_1.32.109.bb
Labels: version-upgrade, backport, auto-integrate, auto-created, scarthgap
